/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-09-28 10:11:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.include;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>파트너스 메인</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/Partners/css/main_style.css\">\r\n");
      out.write("<link rel='stylesheet' href=\"/Partners/css/calendar.css\"/> \r\n");
      out.write("<link rel=\"stylesheet\" href=\"/Partners/css/partners_style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/Partners/css/partners_style2.css\">\r\n");
      out.write("<script src=\"/Partners/js/jquery.js\"></script>\r\n");
      out.write("<script src=\"/Partners/js/javascript.js\"></script>\r\n");
      out.write("<script src=\"/Partners/js/javascript2.js\"></script>\r\n");
      out.write("<script src='/Partners/js/calendar.js'></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#loading {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	top: 0px;\r\n");
      out.write("	left: 0px; \r\n");
      out.write("	display: block;\r\n");
      out.write("	background-color: gray;\r\n");
      out.write("	z-index: 20;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("#loading-image {\r\n");
      out.write("	width:200px;\r\n");
      out.write(" 	position: absolute;\r\n");
      out.write("	top: 40%;\r\n");
      out.write("	left: 50%;\r\n");
      out.write("}\r\n");
      out.write("</style>	\r\n");
      out.write("	\r\n");
      out.write("</head>\r\n");
      out.write("<script>\r\n");
      out.write("	$(window).ready(function() {\r\n");
      out.write("		$('#loading').hide(1000);\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
 
if(session.getAttribute("id")==null){
	out.println("<script>");
	out.println("alert('시간이 만료되어 로그아웃되었습니다!')");
	out.println("location='/Partners/index.do'");
	out.println("</script>");
 }

      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 로딩 아이콘 -->\r\n");
      out.write("<div align=\"center\" id=\"loading\"><img id=\"loading-image\" src=\"/Partners/images/dozip_logo.png\"></div>\r\n");
      out.write("<!-- 좌측 사이드바 영역 -->\r\n");
      out.write("<div id=\"wrap\">\r\n");
      out.write("	<div id=\"side_wrap\">\r\n");
      out.write("			<ul id=\"side_menu\">\r\n");
      out.write("				<li><a href=\"#\" style=\"height:75px;\"></a></li>\r\n");
      out.write("				<li><a href=\"/Partners/index.jsp\">PARTNERS</a></li>\r\n");
      out.write("				<li><a href=\"#\">요&nbsp;&nbsp;금&nbsp;&nbsp;제</a>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"/Partners/interior_Plan/plan.jsp\">요금제안내</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li><a href=\"#\">견적&nbsp;의뢰</a>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"/Partners/bid.do\">입찰의뢰</a></li>\r\n");
      out.write("						<li><a href=\"/Partners/estimate_request/construct_request.jsp\">시공요청</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("				<li><a href=\"#\">견적&nbsp;관리</a>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"/Partners/estimate/estimate_list.jsp\">견적목록</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("				<li><a href=\"#\">내&nbsp;&nbsp;공&nbsp;&nbsp;사</a>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"/Partners/myinterior/interior_List.jsp\">내 공사내역</a></li>\r\n");
      out.write("						<li><a href=\"/Partners/myinterior/schedule_List.jsp\">일정 및 정산관리</a></li>\r\n");
      out.write("						<li><a href=\"/Partners/myinterior/settlement_details.jsp\">정산내역</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("				<li><a href=\"#\">시공&nbsp;사례</a>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"/Partners/upload.do\">등록</a></li>\r\n");
      out.write("						<li><a href=\"/Partners/portfolio_list.do\">수정/삭제</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("				<li><a href=\"#\">광고&nbsp;관리</a>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"/Partners/marketing/marketing.jsp\">노출프로모션</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("				<li><a href=\"#\">고객&nbsp;관리</a>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"/Partners/customer_qna.do\">고객문의</a></li>\r\n");
      out.write("						<li><a href=\"/Partners/customer_review.do\">고객후기</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("				<li><a href=\"#\">My&nbsp;Page</a>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"/Partners/data_manage.do\">내 정보관리</a></li>\r\n");
      out.write("						<li><a href=\"/Partners/pw_change.do\">비밀번호 변경</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("				");
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	<div id=\"cont_wrap\">\r\n");
      out.write("		<header>\r\n");
      out.write("			<div id=\"top_bar\">\r\n");
      out.write("				<div id=top_title>\r\n");
      out.write("					<div>\r\n");
      out.write("					\r\n");
      out.write("					<button id=\"logo_button\" onclick=\"logout_check()\"> <img src=\"/Partners/images/dozip_logo.png\" alt=\"메인로고\"></button>\r\n");
      out.write("						\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>PARTNERS PAGE</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"msg\">\r\n");
      out.write("					<span class=\"hide_1\"> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${businessName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("   님 환영합니다 <span id=\"timer\"></span></span> <span\r\n");
      out.write("						class=\"hide_2\"><input type=\"button\" value=\"로그아웃\"\r\n");
      out.write("						onclick=\"logout_check()\"></span>\r\n");
      out.write("						\r\n");
      out.write("						\r\n");
      out.write("						<script>\r\n");
      out.write("							function logout_check() {\r\n");
      out.write("								var x = confirm('로그아웃 하시겠습니까?');\r\n");
      out.write("								\r\n");
      out.write("								if(x) location='/Partners/partners_logout.do'\r\n");
      out.write("								else return;\r\n");
      out.write("							}\r\n");
      out.write("						</script>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<article id=\"main_cont\">");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
