/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-09-22 04:28:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.portfolio;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class port_005fdetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1663725906238L));
    _jspx_dependants.put("jar:file:/C:/20220607/프로젝트%20관련/teamproject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DoZip/WEB-INF/lib/standard.jar!/META-INF/fn.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("jar:file:/C:/20220607/프로젝트%20관련/teamproject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DoZip/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/DoZip/css/port_detail.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	 <div class=\"clear\"></div>\r\n");
      out.write("      \r\n");
      out.write("   <!-- 본문영역 -->\r\n");
      out.write("   <div class = \"detail_wrap\">\r\n");
      out.write("   <hr>\r\n");
      out.write("      <div class = \"detail_1\">\r\n");
      out.write("         <div class = \"detail_img\">\r\n");
      out.write("            <img id = \"main_img\" src = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${plist[0].pf_photo1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("            <br><br>\r\n");
      out.write("            <div class = \"d_main\">\r\n");
      out.write("               <h2 id = \"d_title\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${plist[0].pf_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h2>\r\n");
      out.write("               <br>\r\n");
      out.write("               <pre id = \"d_location\"><img id = \"d_loca\" src = \"/DoZip/images/portfolio/location_icon.png\"/>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${plist[0].pf_addr1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</pre>\r\n");
      out.write("               <br>\r\n");
      out.write("               <div class = \"d_tags\">\r\n");
      out.write("                  <button type = \"button\" id = \"type\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${plist[0].pf_concept}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</button>\r\n");
      out.write("                  <button type = \"button\" id = \"cate\" >");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${plist[0].pf_subtype}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</button>\r\n");
      out.write("                  <button type = \"button\" id = \"amount\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${plist[0].pf_area}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("평</button>\r\n");
      out.write("                  <button type = \"button\" id = \"price\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${plist[0].pf_cost}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("만원</button>\r\n");
      out.write("                  <button type = \"button\" id = \"time\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${plist[0].pf_period}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("주</button>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class = \"d_check\">\r\n");
      out.write("                  <div class = \"scrap\">\r\n");
      out.write("                     <h3>스크랩하기</h3>\r\n");
      out.write("                     <label class=\"switch\">\r\n");
      out.write("                          <input type=\"checkbox\">\r\n");
      out.write("                          <span class=\"slider round\"></span>\r\n");
      out.write("                     </label>\r\n");
      out.write("                     <p id = \"scrap_no\">Scrap하기</p><p id = \"scrap_ok\" style=\"display:none;\">Scrap완료</p>\r\n");
      out.write("                     <script>\r\n");
      out.write("                        var check = $(\"input[type='checkbox']\");\r\n");
      out.write("                        check.click(function(){\r\n");
      out.write("                              $(\"p\").toggle();\r\n");
      out.write("                        });\r\n");
      out.write("                     </script>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class = \"direct_contact\">\r\n");
      out.write("                     <button type = \"button\" id = \"contact\" onclick = \"openContact()\">업체컨택하기</button>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  ");
      out.write("\r\n");
      out.write("                  <script>\r\n");
      out.write("                     function openContact(){\r\n");
      out.write("                        window.open(\"dir_contact.jsp\",\"_blank\",\r\n");
      out.write("                              \"toolbar = no, menubar = no, scrollbars=no, resizable=no, width=500, height=750, left=0, top=0\");\r\n");
      out.write("                     }\r\n");
      out.write("                  </script>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <br><br>\r\n");
      out.write("      <div class = \"detail_2\">\r\n");
      out.write("         <div class = \"detail_cont1\">\r\n");
      out.write("            <pre id = \"start_cont\"> \r\n");
      out.write("            ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${plist[0].pf_introduction}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("            </pre>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class = \"detail_imgs\">\r\n");
      out.write("            <img id = \"d_imgs\" src = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${plist[0].pf_photo1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("            <img id = \"d_imgs\" src = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${plist[0].pf_photo2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("            <img id = \"d_imgs\" src = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${plist[0].pf_photo3}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("            <img id = \"d_imgs\" src = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${plist[0].pf_photo4}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("            <img id = \"d_imgs\" src = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${plist[0].pf_photo5}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class = \"detail_cont2\">\r\n");
      out.write("            <pre id = \"end_cont\">\r\n");
      out.write("            ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${plist[0].pf_closing}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("            </pre>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <br><br>\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("   <div class = \"comp_card\">\r\n");
      out.write("      <div class=   \"comp_img\">\r\n");
      out.write("         <img id = \"comp_logo\" src = \"/DoZip/images/portfolio/detail/compHC.png\"/>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class = \"comp_name\">\r\n");
      out.write("         <h2>호철 디자인</h2>\r\n");
      out.write("         <pre id = \"comp_loca\">경기 수원시 영통구 광교중앙로 170</pre>\r\n");
      out.write("      </div>   \r\n");
      out.write("      <div class = \"comp_detail\">\r\n");
      out.write("         <button type = \"button\" id = \"comp\" onclick = \"location = 'comp_detail.do'\">더보러가기</button>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <br><br>\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("   \r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/footer.jsp", out, false);
      out.write(' ');
      out.write(' ');
      out.write(' ');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
