/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-09-30 05:12:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.portfolio;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.dozip.vo.PortfolioVO;
import com.dozip.dao.PortfolioDAOImpl;
import com.dozip.vo.PortfolioVO;
import java.util.List;

public final class port_005fmain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:length", org.apache.taglibs.standard.functions.Functions.class, "length", new Class[] {java.lang.Object.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1663725906238L));
    _jspx_dependants.put("jar:file:/C:/20220607/프로젝트%20관련/teamproject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DoZip/WEB-INF/lib/standard.jar!/META-INF/fn.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("jar:file:/C:/20220607/프로젝트%20관련/teamproject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DoZip/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.dozip.vo.PortfolioVO");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.dozip.dao.PortfolioDAOImpl");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/DoZip/css/portfolio.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css\" integrity=\"sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("<link href=\"//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href='https://fonts.googleapis.com/css?family=Anton' rel='stylesheet' type='text/css'>\r\n");
      out.write("<link href='https://fonts.googleapis.com/css?family=Neucha' rel='stylesheet' type='text/css'>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"./js/portfolio.js\"defer></script>\r\n");
      out.write("<script src=\"/DoZip/js/jquery.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"clear\"></div>\r\n");
      out.write("		\r\n");
      out.write("	<!-- 본문영역-->\r\n");
      out.write("	\r\n");
      out.write("	<!-- 프리미엄 기업 리스트-->\r\n");
      out.write("		<div class = \"premium_wrap\">\r\n");
      out.write("			<div class = \"premium_comp\">\r\n");
      out.write("				\r\n");
      out.write("				");
      out.write("\r\n");
      out.write("				<div id=\"wrapper\">\r\n");
      out.write("			      <div id=\"slider-wrap\">\r\n");
      out.write("			          <ul id=\"slider\">\r\n");
      out.write("			             <li>                \r\n");
      out.write("							<img src=\"/DoZip/images/portfolio/banner/final_bannerH.png\">\r\n");
      out.write("			             </li>\r\n");
      out.write("			             \r\n");
      out.write("			             <li>\r\n");
      out.write("							<img src=\"/DoZip/images/portfolio/banner/final_bannerJ.png\">\r\n");
      out.write("			             </li>\r\n");
      out.write("			             \r\n");
      out.write("			             <li>\r\n");
      out.write("							<img src=\"/DoZip/images/portfolio/banner/final_bannerM.png\">\r\n");
      out.write("			             </li>\r\n");
      out.write("			             \r\n");
      out.write("			             <li>\r\n");
      out.write("							<img src=\"/DoZip/images/portfolio/banner/final_bannerS.png\">\r\n");
      out.write("			             </li>\r\n");
      out.write("			          </ul>\r\n");
      out.write("			          \r\n");
      out.write("			           <!--controls-->\r\n");
      out.write("			          <div class=\"btns\" id=\"next\"><i class=\"fa fa-arrow-right\"></i></div>\r\n");
      out.write("			          <div class=\"btns\" id=\"previous\"><i class=\"fa fa-arrow-left\"></i></div>\r\n");
      out.write("			          <div id=\"counter\"></div>\r\n");
      out.write("			          \r\n");
      out.write("			          <div id=\"pagination-wrap\">\r\n");
      out.write("			            <ul>\r\n");
      out.write("			            </ul>\r\n");
      out.write("			          </div>\r\n");
      out.write("			          <!--controls-->  \r\n");
      out.write("                 \r\n");
      out.write("      			</div>\r\n");
      out.write("   			</div>\r\n");
      out.write("   			");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("		<br>	\r\n");
      out.write("	<!-- 드롭다운 버튼 -->\r\n");
      out.write("	<div class = \"port_wrap\">\r\n");
      out.write("		<div class = \"dropdown\">\r\n");
      out.write("			<select name=\"d1\" id=\"dd_group1\">\r\n");
      out.write("				<option selected>주거유형</option>\r\n");
      out.write("				<option value=\"아파트\">아파트</option>\r\n");
      out.write("				<option value=\"빌라\">빌라</option>\r\n");
      out.write("				<option value=\"주택\">주택</option>\r\n");
      out.write("				<option value=\"오피스텔\">오피스텔</option>\r\n");
      out.write("			</select>\r\n");
      out.write("			<select name=\"d2\" id=\"dd_group2\">\r\n");
      out.write("				<option selected>상업유형</option>\r\n");
      out.write("				<option value=\"카페/식당\">카페/식당</option>\r\n");
      out.write("				<option value=\"상가/매장\">상가/매장</option>\r\n");
      out.write("				<option value=\"학원/교육\">학원/교육</option>\r\n");
      out.write("				<option value=\"사무실\">사무실</option>\r\n");
      out.write("				<option value=\"숙박/병원\">숙박/병원</option>\r\n");
      out.write("				<option value = \"간판\">간판</option>\r\n");
      out.write("				<option value = \"기타\">기타</option>\r\n");
      out.write("			</select>\r\n");
      out.write("			<select name=\"d3\" id=\"dd_group3\">\r\n");
      out.write("				<option selected>스타일</option>\r\n");
      out.write("				<option value=\"모던\">모던</option>\r\n");
      out.write("				<option value=\"미니멀\">미니멀</option>\r\n");
      out.write("				<option value=\"내추럴\">내추럴</option>\r\n");
      out.write("				<option value=\"빈티지\">빈티지</option>\r\n");
      out.write("				<option value=\"심플\">심플</option>\r\n");
      out.write("				<option value=\"럭셔리\">럭셔리</option>\r\n");
      out.write("			</select>\r\n");
      out.write("			<select name=\"d4\" id=\"dd_group4\">\r\n");
      out.write("				<option value=\"0\" selected>비용</option>\r\n");
      out.write("				<option value=\"999\">1000만원 이하</option>\r\n");
      out.write("				<option value=\"1000\">1000만원대</option>\r\n");
      out.write("				<option value=\"2000\">2000만원대</option>\r\n");
      out.write("				<option value=\"3000\">3000만원대</option>\r\n");
      out.write("				<option value=\"4000\">4000만원대</option>\r\n");
      out.write("				<option value=\"5000\">5000만원대</option>\r\n");
      out.write("				<option value=\"6000\">6000만원 이상</option>\r\n");
      out.write("			</select>\r\n");
      out.write("			<select name=\"d5\" id=\"dd_group5\">\r\n");
      out.write("				<option value=\"0\" selected>평수</option>\r\n");
      out.write("				<option value=\"10\">10평</option>\r\n");
      out.write("				<option value=\"20\">20평</option>\r\n");
      out.write("				<option value=\"30\">30평</option>\r\n");
      out.write("				<option value=\"40\">40평</option>\r\n");
      out.write("				<option value=\"50\">50평</option>\r\n");
      out.write("				<option value=\"60\">60평 이상</option>\r\n");
      out.write("				\r\n");
      out.write("			</select>\r\n");
      out.write("			\r\n");
      out.write("			<button onclick = \"clear_btn()\" class = \"clear_btn\">초기화</button>			\r\n");
      out.write("		</div>	\r\n");
      out.write("		<!-- 드롭다운 끝 -->\r\n");
      out.write("		\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("		<script>\r\n");
      out.write("			function clear_btn(){\r\n");
      out.write("				document.getElementById(\"dd_group1\").value = \"주거유형\";\r\n");
      out.write("				document.getElementById(\"dd_group2\").value = \"상업유형\";\r\n");
      out.write("				document.getElementById(\"dd_group3\").value = \"스타일\";\r\n");
      out.write("				document.getElementById(\"dd_group4\").value = 0;\r\n");
      out.write("				document.getElementById(\"dd_group5\").value = 0;\r\n");
      out.write("				$('#dd_group1').show();\r\n");
      out.write("				$('#dd_group2').show();\r\n");
      out.write("				$('.card').show();\r\n");
      out.write("			}\r\n");
      out.write("		</script>\r\n");
      out.write("		\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("		<script>\r\n");
      out.write("			function searchTag(){\r\n");
      out.write("				var sub1 = document.getElementById(\"dd_group1\").value;\r\n");
      out.write("				var sub2 = document.getElementById(\"dd_group2\").value;\r\n");
      out.write("				var con = document.getElementById(\"dd_group3\").value;\r\n");
      out.write("				var cost = document.getElementById(\"dd_group4\").value;\r\n");
      out.write("				var area = document.getElementById(\"dd_group5\").value;\r\n");
      out.write("				\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					type:\"post\", \r\n");
      out.write("					url:'port_search.do', \r\n");
      out.write("					datatype: \"json\",\r\n");
      out.write("					data:{\r\n");
      out.write("						sub1 : sub1,\r\n");
      out.write("						sub2 : sub2,\r\n");
      out.write("						con : con,\r\n");
      out.write("						area : area,\r\n");
      out.write("						cost : cost\r\n");
      out.write("					}, success: function(data) {\r\n");
      out.write("						alert('댓글등록완료!');\r\n");
      out.write("						var result = data.json;\r\n");
      out.write("						$.each(result,function(idx,val){\r\n");
      out.write("							console.log(idx+\" \"+val.con);\r\n");
      out.write("						});\r\n");
      out.write("						\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("			}\r\n");
      out.write("		</script>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("		<script type=\"text/javascript\">\r\n");
      out.write("		jQuery(function(event) {\r\n");
      out.write("		    $('.search_Btn').on('click',function(event) {\r\n");
      out.write("		        var val = $('#keyword').val();\r\n");
      out.write("		        if (val == \"\") {\r\n");
      out.write("		            $('.card').show();\r\n");
      out.write("		        } else {\r\n");
      out.write("		        	if(\".bname:contains('\"+val+\"')\") {\r\n");
      out.write("			            $('.card').hide();\r\n");
      out.write("			            $(\".card:contains('\"+val+\"')\").show();\r\n");
      out.write("		        	}else{\r\n");
      out.write("		        		$('.card').hide();\r\n");
      out.write("		        	}\r\n");
      out.write("		        }\r\n");
      out.write("		    });\r\n");
      out.write("		});\r\n");
      out.write("		</script> \r\n");
      out.write("		<!-- 검색창 -->\r\n");
      out.write("		<div class = \"search_wrap\">\r\n");
      out.write("			<div class = \"search\">\r\n");
      out.write("				<input type = \"text\" name = \"keyword\" id=\"keyword\" placeholder=\"업체명을 입력하세요\">\r\n");
      out.write("				<button  class = \"search_Btn\">\r\n");
      out.write("					<i class = \"fas fa-search\"></i>\r\n");
      out.write("				</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>		\r\n");
      out.write("			\r\n");
      out.write("		\r\n");
      out.write("		<!-- 카드 리스트 -->\r\n");
      out.write("		<div class=\"construction_list\">\r\n");
      out.write("			<div class=\"top_utile\">\r\n");
      out.write("				<p class=\"top_title\">포트폴리오</p> \r\n");
      out.write(" 			</div>\r\n");
      out.write(" 			\r\n");
      out.write(" 			<!-- 반복문 시작-->\r\n");
      out.write("			<div class=\"cards-list\">\r\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			</div> \r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write(" 		</div>\r\n");
      out.write(" 		<br>\r\n");
      out.write(" 		<br>\r\n");
      out.write(" 		\r\n");
      out.write("				\r\n");
      out.write(" 		\r\n");
      out.write("\r\n");
      out.write('	');
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/footer.jsp", out, false);
      out.write('	');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /portfolio/port_main.jsp(204,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty plist}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				");
          if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /portfolio/port_main.jsp(205,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("i");
      // /portfolio/port_main.jsp(205,4) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setBegin(0);
      // /portfolio/port_main.jsp(205,4) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setEnd(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:length(plist)-1}", int.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0)).intValue());
      // /portfolio/port_main.jsp(205,4) name = step type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setStep(1);
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("					<div class=\"card\">\r\n");
            out.write("					  <div class=\"card_image\"> \r\n");
            out.write("					  	<img class = \"ho\" onclick = \"location.href='port_detail.do?pf_no=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${plist[i].pf_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("';\" src= '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${plist[i].pf_photo1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("'/> \r\n");
            out.write("					  	");
            out.write("\r\n");
            out.write("					  </div>\r\n");
            out.write("					  <div class=\"card_title\">\r\n");
            out.write("						  	<li id = \"bname\" style=\"display: none\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${plist[i].businessName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</li>\r\n");
            out.write("						   	<li class = \"corp\" id=\"pf_title\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${plist[i].pf_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</li>						   	\r\n");
            out.write("						   	<li class = \"card_tag\">\r\n");
            out.write("						   		<span id=\"pf_subtype\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${plist[i].pf_subtype}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("						   		<span id=\"pf_concept\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${plist[i].pf_concept}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("						   		<span id=\"pf_area\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${plist[i].pf_area}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("평</span>\r\n");
            out.write("						   		<span id=\"pf_cost\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${plist[i].pf_cost}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("만원대</span>\r\n");
            out.write("						   	</li>\r\n");
            out.write("					  </div>\r\n");
            out.write("					</div>\r\n");
            out.write("				");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /portfolio/port_main.jsp(227,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty plist}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<div id = \"none_pf\">포트폴리오 목록이 없습니다</div>\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
