/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-09-29 05:02:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.apply;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class applicationSheet5_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"./css/apply_style_05.css\">  \r\n");
      out.write("  <script src=\"./js/apply.js\" defer></script>\r\n");
      out.write("  <script src=\"./js/jquery.js\"></script>\r\n");
      out.write("  <script src=\"http://code.jquery.com/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("  <script src=\"./js/sessionStorage.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <title>Step 5</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<form method=\"post\">\r\n");
      out.write("\r\n");
      out.write("  <div id=\"estimate_step05\">\r\n");
      out.write("    <section aria-label=\"견적요청\" class=\"estimate_yourcost\">\r\n");
      out.write("      <div class=\"title\">\r\n");
      out.write("        <h2>**고객님의 견적요청내용입니다.</h2><h3></h3>\r\n");
      out.write("      </div>\r\n");
      out.write("          <p class=\"subtitle\">견적요청내용을 확인하시고 맞다면 요청을 보내주세요.</p><br />\r\n");
      out.write("      <div class=\"estimate_box\">\r\n");
      out.write("        <h3>고객님의 요청내용</h3>\r\n");
      out.write("\r\n");
      out.write("        <h4>고객</h4>\r\n");
      out.write("        <h4>전화번호</h4>\r\n");
      out.write("        <h4>공간 유형</h4>\r\n");
      out.write("        <p>주거</p>\r\n");
      out.write("        <h4>건물 유형</h4>\r\n");
      out.write("        <p>아파트</p>\r\n");
      out.write("        <h4>면적 (공급면적)</h4>\r\n");
      out.write("        <p>123평 (3.3m2)</p>\r\n");
      out.write("        <h4>세부선택</h4>\r\n");
      out.write("        <p>바닥 : 장판</p>\r\n");
      out.write("        <p>조명 : 전체교체</p>\r\n");
      out.write("        <h4>고객님 예산</h4>\r\n");
      out.write("        <p>123,123만원</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      </section>    \r\n");
      out.write("   <div class=\"nextpage\">\r\n");
      out.write("    <button class=\"button\" id=\"go-back\" onclick=\"location.href='estimate_apply4.do'\">이전</button>\r\n");
      out.write("    <button class=\"button\" type=\"submit\" id=\"go-next\" onclick=\"test()\">진행하기</button>\r\n");
      out.write("   </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  </form>\r\n");
      out.write("</body>\r\n");
      out.write(" ");
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
