/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-09-30 05:12:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.apply;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class applicationSheet_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/apply_style.css\" />\r\n");
      out.write("<script src=\"./js/apply.js\" defer></script>\r\n");
      out.write("<script src=\"./js/jquery.js\"></script>\r\n");
      out.write("<script src=\"./js/sessionStorage.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("    <title>인테리어 견적 신청서</title>\r\n");
      out.write("  <body>\r\n");
      out.write("    <article id=\"estimate_step01\">\r\n");
      out.write("     <form method=\"post\" action=\"estimate_apply_ok.do\" onsubmit='return apply01_check()'>\r\n");
      out.write("      <div>\r\n");
      out.write("        <section aria-label=\"공간 유형 선택\" class=\"building_types\">\r\n");
      out.write("          <div class=\"title\">\r\n");
      out.write("          <h2>어떤 공간의 시공을 원하시나요?</h2><h3>1/4</h3>\r\n");
      out.write("          </div>\r\n");
      out.write("          <br/>\r\n");
      out.write("          <div class=\"estimate_box\">\r\n");
      out.write("          <h3>공간 유형</h3>\r\n");
      out.write("            <input type=\"radio\" value=\"주거\" id=\"1\" name=\"est_zoning\" checked><label for=\"1\">주거</label>\r\n");
      out.write("            <input type=\"radio\" value=\"상가\" id=\"2\" name=\"est_zoning\"><label for=\"2\">상가</label>\r\n");
      out.write("        </section>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"estimate_box\">\r\n");
      out.write("        <h3>건물 유형</h3>\r\n");
      out.write("        <div id = \"type01\" >\r\n");
      out.write("          <div>\r\n");
      out.write("          <input type=\"radio\" id=\"ty1\" name=\"est_use\" value=\"아파트\"><label for=\"ty1\">아파트</label>\r\n");
      out.write("          <input type=\"radio\" id=\"ty2\" name=\"est_use\" value=\"빌라\"><label for=\"ty2\">빌라</label>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div>\r\n");
      out.write("            <input type=\"radio\" id=\"ty3\" name=\"est_use\" value=\"주택\"><label for=\"ty3\">주택</label>\r\n");
      out.write("            <input type=\"radio\" id=\"ty4\" name=\"est_use\" value=\"오피스텔\"><label for=\"ty4\">오피스텔</label>\r\n");
      out.write("          </div>\r\n");
      out.write("          </div>\r\n");
      out.write("           <div id=\"type02\" style=\"display: none;\">\r\n");
      out.write("            <div>\r\n");
      out.write("            <input type=\"radio\" id=\"ty5\" name=\"est_use\" value=\"사무실\"><label for=\"ty5\">사무실</label>\r\n");
      out.write("            <input type=\"radio\" id=\"ty6\" name=\"est_use\" value=\"상가/매장\"><label for=\"ty6\">상가/매장</label>\r\n");
      out.write("            </div>\r\n");
      out.write("            <input type=\"radio\" id=\"ty7\" name=\"est_use\" value=\"카페/식당\"><label for=\"ty7\">카페/식당</label>\r\n");
      out.write("            <input type=\"radio\" id=\"ty8\" name=\"est_use\" value=\"학원/교육\"><label for=\"ty8\">학원/교육</label>\r\n");
      out.write("            <div>\r\n");
      out.write("            <input type=\"radio\" id=\"ty9\" name=\"est_use\" value=\"숙박/병원\"><label for=\"ty9\">숙박/병원</label>\r\n");
      out.write("            <input type=\"radio\" id=\"ty10\" name=\"est_use\" value=\"간판\"><label for=\"ty10\">간판</label>\r\n");
      out.write("            </div>\r\n");
      out.write("            <input type=\"radio\" id=\"ty11\" name=\"est_use\" value=\"기타\"><label for=\"ty11\">기타</label>\r\n");
      out.write("           </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- id : 고유한 식별 목적\r\n");
      out.write("           class : 재사용을 목적\r\n");
      out.write("           name : 컨트롤 요소값(value)을 서버로 전송하기위함-->\r\n");
      out.write("      <div class = \"estimate_calculator\">\r\n");
      out.write("        <h3>평수 (공급면적)</h3><br/>\r\n");
      out.write("        <input type=\"text\" id=\"cal1\" name=\"areaP\" maxlength=\"3\" placeholder=0 onclick=\"change()\" onkeyup=\"calculator(1);\" value=\"0\">&nbsp;평 -&nbsp;<input type=\"text\" id=\"cal2\" name=\"areaM\" placeholder=0 onkeyup=\"calculator(2);\" value=\"0\">&nbsp;m2\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"areaBoxComponent\">\r\n");
      out.write("        <h3>원하는 공간 선택</h3>\r\n");
      out.write("        <div class=\"123\">\r\n");
      out.write("          <input type=\"checkbox\" id=\"allCk\" name=\"checkAll\" class=\"checkbox\" data-name=\"전체선택\">\r\n");
      out.write("          <input type=\"checkbox\" id=\"wall\" name=\"check\" data-name=\"도배/벽\" value=\"도배/벽\" class =\"checkbox\"/>\r\n");
      out.write("          <input type=\"checkbox\" id=\"floor\" name=\"check\" data-name=\"바닥\" value=\"바닥\" class =\"checkbox\"/>\r\n");
      out.write("          <input type=\"checkbox\" id=\"kitchen\" name=\"check\" data-name=\"주방\" value=\"주방\" class =\"checkbox\"/>\r\n");
      out.write("          <input type=\"checkbox\" id=\"washroom\" name=\"check\" data-name=\"욕실\" value=\"욕실\" class =\"checkbox\"/>\r\n");
      out.write("          <input type=\"checkbox\" id=\"porch\" name=\"check\" data-name=\"현관\" value=\"현관\" class =\"checkbox\"/>\r\n");
      out.write("          <input type=\"checkbox\" id=\"window\" name=\"check\" data-name=\"발코니/샷시\" value=\"발코니/샷시\" class =\"checkbox\"/>\r\n");
      out.write("          <input type=\"checkbox\" id=\"light\" name=\"check\" data-name=\"조명\" value=\"조명\" class =\"checkbox\"/>\r\n");
      out.write("          <input type=\"checkbox\" id=\"door\" name=\"check\" data-name=\"문\" value=\"문\" class =\"checkbox\"/>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- 상세 시공 도배/벽 -->\r\n");
      out.write("      <article class=\"section_detail_select\" id=\"detail01\" name=\"detail\" style=\"display: none;\">\r\n");
      out.write("      <div class = \"detail_select\">\r\n");
      out.write("            <h3 class=\"detail_title\">도배/벽</h3>\r\n");
      out.write("        <ul aria-label=\"도배/벽 선택 목록\" class=\"detail_item\">\r\n");
      out.write("            <li class=\"btn_line_detail\">\r\n");
      out.write("                <input type=\"radio\" id=\"group_wallpaper_item_0\" name=\"group_wallpaper_item\" value=\"합지\">\r\n");
      out.write("                <label for=\"group_wallpaper_item_0\">\r\n");
      out.write("                    <span class=\"h4 select_detail__title\">합지</span>\r\n");
      out.write("                    <p class=\"select_detail__desc\">일반 종이 벽지로 친환경적</p>\r\n");
      out.write("                    <span class=\"expect_price\">326만원~</span>\r\n");
      out.write("                </label>\r\n");
      out.write("\r\n");
      out.write("                <input type=\"radio\" id=\"group_wallpaper_item_1\" name=\"group_wallpaper_item\" value=\"실크\">\r\n");
      out.write("                <label for=\"group_wallpaper_item_1\">\r\n");
      out.write("                    <span class=\"h4 select_detail__title\">실크</span>\r\n");
      out.write("                    <p class=\"select_detail__desc\">코팅된 종이로 오염에 강함</p>\r\n");
      out.write("                    <span class=\"expect_price\">445만원~</span>\r\n");
      out.write("                </label></li>\r\n");
      out.write("            <li class=\"btn_line_detail\">\r\n");
      out.write("                <input type=\"radio\" id=\"group_wallpaper_item_2\" name=\"group_wallpaper_item\" value=\"합지+실크\">\r\n");
      out.write("                <label for=\"group_wallpaper_item_2\">\r\n");
      out.write("                    <span class=\"h4 select_detail__title\">합지+실크</span>\r\n");
      out.write("                    <p class=\"select_detail__desc\">거실 실크+방 합지 조합</p>\r\n");
      out.write("                    <span class=\"expect_price\">374만원~</span>\r\n");
      out.write("                </label>\r\n");
      out.write("\r\n");
      out.write("                <input type=\"radio\" id=\"group_wallpaper_item_3\" name=\"group_wallpaper_item\" value=\"타일\">\r\n");
      out.write("                <label for=\"group_wallpaper_item_3\">\r\n");
      out.write("                    <span class=\"h4 select_detail__title\">타일</span>\r\n");
      out.write("                    <p class=\"select_detail__desc\">내구성이 강하고 고급스러움</p>\r\n");
      out.write("                </label></li>\r\n");
      out.write("            <li class=\"btn_line_detail\">\r\n");
      out.write("                <input type=\"radio\" id=\"group_wallpaper_item_4\" name=\"group_wallpaper_item\" value=\"대리석\">\r\n");
      out.write("                <label for=\"group_wallpaper_item_4\">\r\n");
      out.write("                    <span class=\"h4 select_detail__title\">대리석</span>\r\n");
      out.write("                    <p class=\"select_detail__desc\">천연소재로 고급스러움</p>\r\n");
      out.write("                    <span class=\"expect_price\">360만원~</span>\r\n");
      out.write("                </label>\r\n");
      out.write("\r\n");
      out.write("                <input type=\"radio\" id=\"group_wallpaper_item_5\" name=\"group_wallpaper_item\" value=\"페인트\">\r\n");
      out.write("                <label for=\"group_wallpaper_item_5\">\r\n");
      out.write("                    <span class=\"h4 select_detail__title\">페인트</span>\r\n");
      out.write("                    <p class=\"select_detail__desc\">다양한 색 조합 가능</p>\r\n");
      out.write("                </label></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <h4 class=\"detail_item\">추가선택</h4>\r\n");
      out.write("        <ul class=\"clearfix detail_item\">\r\n");
      out.write("            <li class=\"btn_line_detail\"><input type=\"checkbox\" id=\"group_wallpaper_option_0\" value=\"몰딩\">\r\n");
      out.write("                <label for=\"group_wallpaper_option_0\">\r\n");
      out.write("                    <span class=\"h4 select_detail__title\">몰딩</span>\r\n");
      out.write("                    <p class=\"select_detail__desc\">천장과 벽 사이의 마감</p>\r\n");
      out.write("                </label></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </article>\r\n");
      out.write("\r\n");
      out.write("    <!-- 상세 시공 바닥 -->\r\n");
      out.write("    <article class=\"section_detail_select\" id=\"detail02\" name=\"detail\" style=\"display: none;\">\r\n");
      out.write("    <div class = \"detail_select\">\r\n");
      out.write("      <h3 class=\"detail_title\">바닥</h3>\r\n");
      out.write("  <ul aria-label=\"바닥 선택 목록\" class=\"detail_item\">\r\n");
      out.write("      <li class=\"btn_line_detail\">\r\n");
      out.write("          <input type=\"radio\" id=\"group_floor_item_0\" name=\"group_floor_item\" value=\"장판\">\r\n");
      out.write("          <label for=\"group_floor_item_0\">\r\n");
      out.write("              <span class=\"h4 select_detail__title\">장판</span>\r\n");
      out.write("              <p class=\"select_detail__desc\">오염과손상에강함</p>\r\n");
      out.write("              <span class=\"expect_price\">240만원~</span>\r\n");
      out.write("          </label>\r\n");
      out.write("          <input type=\"radio\" id=\"group_floor_item_1\" name=\"group_floor_item\" value=\"강마루\">\r\n");
      out.write("          <label for=\"group_floor_item_1\">\r\n");
      out.write("              <span class=\"h4 select_detail__title\">강마루</span>\r\n");
      out.write("              <p class=\"select_detail__desc\">원목느낌의 코팅합판마루</p>\r\n");
      out.write("              <span class=\"expect_price\">592만원~</span>\r\n");
      out.write("          </label></li>\r\n");
      out.write("\r\n");
      out.write("      <li class=\"btn_line_detail\">\r\n");
      out.write("          <input type=\"radio\" id=\"group_floor_item_2\" name=\"group_floor_item\" value=\"타일\">\r\n");
      out.write("          <label for=\"group_floor_item_2\">\r\n");
      out.write("              <span class=\"h4 select_detail__title\">타일</span>\r\n");
      out.write("              <p class=\"select_detail__desc\">내구성이강하고고급스러움</p>\r\n");
      out.write("              <span class=\"expect_price\">380만원~</span>\r\n");
      out.write("          </label>\r\n");
      out.write("          <input type=\"radio\" id=\"group_floor_item_3\" name=\"group_floor_item\" value=\"포세린타일\">\r\n");
      out.write("          <label for=\"group_floor_item_3\">\r\n");
      out.write("              <span class=\"h4 select_detail__title\">포세린타일</span>\r\n");
      out.write("              <p class=\"select_detail__desc\">내구성이 강하고 고급스러움</p>\r\n");
      out.write("              <span class=\"expect_price\">1000만원~</span>\r\n");
      out.write("          </label></li>\r\n");
      out.write("\r\n");
      out.write("      <li class=\"btn_line_detail\">\r\n");
      out.write("          <input type=\"radio\" id=\"group_floor_item_4\" name=\"group_floor_item\" value=\"대리석\">\r\n");
      out.write("          <label for=\"group_floor_item_4\">\r\n");
      out.write("              <span class=\"h4 select_detail__title\">대리석</span>\r\n");
      out.write("              <p class=\"select_detail__desc\">천연소재로 고급스러움</p>\r\n");
      out.write("              <span class=\"expect_price\">360만원~</span>\r\n");
      out.write("          </label>\r\n");
      out.write("          </li>\r\n");
      out.write("  </ul>\r\n");
      out.write("  <h4 class=\"detail_item\">추가선택</h4>\r\n");
      out.write("  <ul class=\"clearfix detail_item\">\r\n");
      out.write("      <li class=\"btn_line_detail\"><input type=\"checkbox\" id=\"group_floor_option_1\" value=\"걸레받이\">\r\n");
      out.write("          <label for=\"group_floor_option_1\">\r\n");
      out.write("              <span class=\"h4 select_detail__title\">걸레받이</span>\r\n");
      out.write("              <p class=\"select_detail__desc\">벽과 바닥재 사이의마감</p>\r\n");
      out.write("          </label></li>\r\n");
      out.write("  </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("</article>\r\n");
      out.write("\r\n");
      out.write("<!-- 상세 시공 주방 -->\r\n");
      out.write("<article class=\"section_detail_select\" id=\"detail03\" name=\"detail\" style=\"display: none;\">\r\n");
      out.write("<div class = \"detail_select\">\r\n");
      out.write("  <h3 class=\"detail_title\">주방</h3>\r\n");
      out.write("<ul aria-label=\"주방 선택 목록\" class=\"detail_item\">\r\n");
      out.write(" <li class=\"btn_line_detail\">\r\n");
      out.write("    <input type=\"checkbox\" id=\"group_kitchen_item_0\" name=\"group_kitchen_item\" value=\"전체교체\">\r\n");
      out.write("     <label for=\"group_kitchen_item_0\">\r\n");
      out.write("      <span class=\"h4 select_detail__title\">전체선택</span>\r\n");
      out.write("       <span class=\"expect_price\">550만원~</span>\r\n");
      out.write("     </label>\r\n");
      out.write("    <input type=\"checkbox\" id=\"group_kitchen_item_1\" name=\"group_kitchen_item\" value=\"필름\">\r\n");
      out.write("     <label for=\"group_kitchen_item_1\">\r\n");
      out.write("      <span class=\"h4 select_detail__title\">필름</span>\r\n");
      out.write("       <p class=\"select_detail__desc\">상부장,하부장등필름시공</p>\r\n");
      out.write("       <span class=\"expect_price\">550만원~</span>\r\n");
      out.write("     </label>\r\n");
      out.write(" </li>\r\n");
      out.write("\r\n");
      out.write("  <li class=\"btn_line_detail\">\r\n");
      out.write("      <input type=\"checkbox\" id=\"group_kitchen_item_2\" name=\"group_kitchen_item\" value=\"타일\">\r\n");
      out.write("      <label for=\"group_kitchen_item_2\">\r\n");
      out.write("          <span class=\"h4 select_detail__title\">타일</span>\r\n");
      out.write("          <p class=\"select_detail__desc\">벽면타일교체</p>\r\n");
      out.write("          <span class=\"expect_price\">45만원~</span>\r\n");
      out.write("      </label>\r\n");
      out.write("      <input type=\"checkbox\" id=\"group_kitchen_item_3\" name=\"group_kitchen_item\" value=\"싱크대\">\r\n");
      out.write("      <label for=\"group_kitchen_item_3\">\r\n");
      out.write("          <span class=\"h4 select_detail__title\">싱크대</span>\r\n");
      out.write("          <p class=\"select_detail__desc\">상부장,하부장만 교체</p>\r\n");
      out.write("      </label></li>\r\n");
      out.write("\r\n");
      out.write("  <li class=\"btn_line_detail\">\r\n");
      out.write("      <input type=\"checkbox\" id=\"group_kitchen_item_4\" name=\"group_kitchen_item\" value=\"가구\">\r\n");
      out.write("      <label for=\"group_kitchen_item_4\">\r\n");
      out.write("          <span class=\"h4 select_detail__title\">가구</span>\r\n");
      out.write("          <p class=\"select_detail__desc\">내장고장등맞춤가구제작</p>\r\n");
      out.write("      </label>\r\n");
      out.write("      <input type=\"checkbox\" id=\"group_kitchen_item_5\" name=\"group_kitchen_item\" value=\"아일랜드식탁\">\r\n");
      out.write("      <label for=\"group_kitchen_item_5\">\r\n");
      out.write("          <span class=\"h4 select_detail__title\">아일랜드식탁</span>\r\n");
      out.write("          <span class=\"expect_price\">120만원~</p>\r\n");
      out.write("      </label></li>\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("</article>\r\n");
      out.write("\r\n");
      out.write("<!-- 상세 시공 욕실 -->\r\n");
      out.write("<article class=\"section_detail_select\" id=\"detail04\" name=\"detail\" style=\"display: none;\">\r\n");
      out.write("<div class = \"detail_select\">\r\n");
      out.write("    <h3 class=\"detail_title\">욕실</h3>\r\n");
      out.write("  <ul aria-label=\"욕실 선택 목록\" class=\"detail_item\">\r\n");
      out.write("    <li class=\"btn_line_detail\">\r\n");
      out.write("        <input type=\"checkbox\" id=\"group_washroom_item_0\" name=\"group_washroom_item\" value=\"전체교체\">\r\n");
      out.write("        <label for=\"group_washroom_item_0\">\r\n");
      out.write("            <span class=\"h4 select_detail__title\">전체교체</span>\r\n");
      out.write("            <span class=\"expect_price\">420만원~</span>\r\n");
      out.write("        </label>\r\n");
      out.write("        <input type=\"checkbox\" id=\"group_washroom_item_1\" name=\"group_washroom_item\" value=\"수납장/선반\">\r\n");
      out.write("        <label for=\"group_washroom_item_1\">\r\n");
      out.write("            <span class=\"h4 select_detail__title\">수납장/선반</span>\r\n");
      out.write("            </label></li>\r\n");
      out.write("        <li class=\"btn_line_detail\">\r\n");
      out.write("            <input type=\"checkbox\" id=\"group_washroom_item_2\" name=\"group_washroom_item\" value=\"도기\">\r\n");
      out.write("            <label for=\"group_washroom_item_2\">\r\n");
      out.write("                <span class=\"h4 select_detail__title\">도기</span>\r\n");
      out.write("                <p class=\"select_detail__desc\">세면대,변기등도기만교체</p>\r\n");
      out.write("                <span class=\"expect_price\">64만원~</span>\r\n");
      out.write("                </label></li>\r\n");
      out.write("    <li class=\"btn_line_detail\">\r\n");
      out.write("        <input type=\"checkbox\" id=\"group_washroom_item_3\" name=\"group_washroom_item\" value=\"타일\">\r\n");
      out.write("        <label for=\"group_washroom_item_3\">\r\n");
      out.write("            <span class=\"h4 select_detail__title\">타일</span>\r\n");
      out.write("            <p class=\"select_detail__desc\">바닥과벽면타일교체</p>\r\n");
      out.write("            <span class=\"expect_price\">322만원~</span>\r\n");
      out.write("        </label></li>\r\n");
      out.write("  </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("  </article>\r\n");
      out.write("  \r\n");
      out.write("<!-- 상세 시공 현관 -->\r\n");
      out.write("<article class=\"section_detail_select\" id=\"detail05\" name=\"detail\" style=\"display: none;\">\r\n");
      out.write("<div class = \"detail_select\">\r\n");
      out.write("    <h3 class=\"detail_title\">현관</h3>\r\n");
      out.write("  <ul aria-label=\"욕실 선택 목록\" class=\"detail_item\">\r\n");
      out.write("    <li class=\"btn_line_detail\">\r\n");
      out.write("        <input type=\"checkbox\" id=\"group_porch_item_0\" name=\"group_porch_item\" value=\"신발장\">\r\n");
      out.write("        <label for=\"group_porch_item_0\">\r\n");
      out.write("            <span class=\"h4 select_detail__title\">신발장</span>\r\n");
      out.write("            <span class=\"expect_price\">128만원~</span>\r\n");
      out.write("        </label>\r\n");
      out.write("        <input type=\"checkbox\" id=\"group_porch_item_1\" name=\"group_porch_item\" value=\"타일\">\r\n");
      out.write("        <label for=\"group_porch_item_1\">\r\n");
      out.write("            <span class=\"h4 select_detail__title\">타일</span>\r\n");
      out.write("            <span class=\"expect_price\">24만원~</span>\r\n");
      out.write("            </label></li>\r\n");
      out.write("        <li class=\"btn_line_detail\">\r\n");
      out.write("            <input type=\"checkbox\" id=\"group_porch_item_2\" name=\"group_porch_item\" value=\"가벽설치\">\r\n");
      out.write("            <label for=\"group_porch_item_2\">\r\n");
      out.write("                <span class=\"h4 select_detail__title\">가벽설치</span>\r\n");
      out.write("                <span class=\"expect_price\">60만원~</span>\r\n");
      out.write("                </label>\r\n");
      out.write("                <input type=\"checkbox\" id=\"group_porch_item_3\" name=\"group_porch_item\" value=\"필름\">\r\n");
      out.write("                <label for=\"group_porch_item_3\">\r\n");
      out.write("                    <span class=\"h4 select_detail__title\">필름</span>\r\n");
      out.write("                    <span class=\"expect_price\">60만원~</span>\r\n");
      out.write("                </label>\r\n");
      out.write("            </li>\r\n");
      out.write("    <li class=\"btn_line_detail\">\r\n");
      out.write("        <input type=\"checkbox\" id=\"group_porch_item_4\" name=\"group_porch_item\" value=\"중문\">\r\n");
      out.write("        <label for=\"group_porch_item_4\">\r\n");
      out.write("            <span class=\"h4 select_detail__title\">중문</span>\r\n");
      out.write("            <span class=\"expect_price\">130만원~</span>\r\n");
      out.write("        </label>\r\n");
      out.write("    </li>\r\n");
      out.write("  </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("  </article>\r\n");
      out.write("  <!-- 상세 시공 발코니/샷시 -->\r\n");
      out.write("<article class=\"section_detail_select\" id=\"detail06\" name=\"detail\" style=\"display: none;\">\r\n");
      out.write("<div class = \"detail_select\">\r\n");
      out.write("    <h3 class=\"detail_title\">발코니/샷시</h3>\r\n");
      out.write("  <ul aria-label=\"발코니/샷시 선택 목록\" class=\"detail_item\">\r\n");
      out.write("    <li class=\"btn_line_detail\">\r\n");
      out.write("        <input type=\"radio\" id=\"group_window_item_0\" name=\"group_window_item\" value=\"전체교체\">\r\n");
      out.write("        <label for=\"group_window_item_0\">\r\n");
      out.write("            <span class=\"h4 select_detail__title\">전체교체</span>\r\n");
      out.write("            <p class=\"select_detail__desc\">내창/외창모두철거후교체</p>\r\n");
      out.write("            <span class=\"expect_price\">1720만원~</span>\r\n");
      out.write("        </label></li>\r\n");
      out.write("        <li class=\"btn_line_detail\">\r\n");
      out.write("        <input type=\"radio\" id=\"group_window_item_1\" name=\"group_window_item\" value=\"부분교체\">\r\n");
      out.write("        <label for=\"group_window_item_1\">\r\n");
      out.write("            <span class=\"h4 select_detail__title\">부분교체</span>\r\n");
      out.write("            <p class=\"select_detail__desc\">부분적으로철거후교체</p>\r\n");
      out.write("            <span class=\"expect_price\">528만원~</span>\r\n");
      out.write("            </label></li>\r\n");
      out.write("        <li class=\"btn_line_detail\">\r\n");
      out.write("            <input type=\"radio\" id=\"group_window_item_2\" name=\"group_window_item\" value=\"필름만시공\">\r\n");
      out.write("            <label for=\"group_window_item_2\">\r\n");
      out.write("                <span class=\"h4 select_detail__title\">필름만시공</span>\r\n");
      out.write("                <p class=\"select_detail__desc\">창들에필름만시공</p>\r\n");
      out.write("                <span class=\"expect_price\">304만원~</span>\r\n");
      out.write("                </label>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <h4 class=\"detail_item\">추가선택</h4>\r\n");
      out.write("        <ul class=\"clearfix detail_item\">\r\n");
      out.write("            <li class=\"btn_line_detail\"><input type=\"checkbox\" id=\"group_window_option_0\" value=\"페인트\">\r\n");
      out.write("                <label for=\"group_window_option_0\">\r\n");
      out.write("                    <span class=\"h4 select_detail__title\">페인트</span>\r\n");
      out.write("                    <p class=\"select_detail__desc\">천장과 벽 사이의 마감</p>\r\n");
      out.write("                </label>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("  </article>\r\n");
      out.write("\r\n");
      out.write("  <!-- 상세 시공 조명 -->\r\n");
      out.write("<article class=\"section_detail_select\" id=\"detail07\" name=\"detail\" style=\"display: none;\">\r\n");
      out.write("<div class = \"detail_select\">\r\n");
      out.write("    <h3 class=\"detail_title\">조명</h3>\r\n");
      out.write("  <ul aria-label=\"조명 선택 목록\" class=\"detail_item\">\r\n");
      out.write("    <li class=\"btn_line_detail\">\r\n");
      out.write("        <input type=\"radio\" id=\"group_light_item_0\" name=\"group_light_item\" value=\"전체교체\">\r\n");
      out.write("        <label for=\"group_light_item_0\">\r\n");
      out.write("            <span class=\"h4 select_detail__title\">전체교체</span>\r\n");
      out.write("            <p class=\"select_detail__desc\">새로운위치에교체</p>\r\n");
      out.write("            <span class=\"expect_price\">449만원~</span>\r\n");
      out.write("        </label></li>\r\n");
      out.write("        <li class=\"btn_line_detail\">\r\n");
      out.write("        <input type=\"radio\" id=\"group_light_item_1\" name=\"group_light_item\" value=\"조명,스위치,콘센트만\">\r\n");
      out.write("        <label for=\"group_light_item_1\">\r\n");
      out.write("            <span class=\"h4 select_detail__title\">조명,스위치,콘센트만</span>\r\n");
      out.write("            <p class=\"select_detail__desc\">기존위치에교체</p>\r\n");
      out.write("            <span class=\"expect_price\">158만원~</span>\r\n");
      out.write("            </label></li>\r\n");
      out.write("        <li class=\"btn_line_detail\">\r\n");
      out.write("            <input type=\"radio\" id=\"group_light_item_2\" name=\"group_light_item\" value=\"전기공사만\">\r\n");
      out.write("            <label for=\"group_light_item_2\">\r\n");
      out.write("                <span class=\"h4 select_detail__title\">전기공사만</span>\r\n");
      out.write("                <p class=\"select_detail__desc\">원하는위치에전기공사</p>\r\n");
      out.write("                <span class=\"expect_price\">96만원~</span>\r\n");
      out.write("                </label>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("  </article>\r\n");
      out.write("  \r\n");
      out.write("  <!-- 상세 시공 문 -->\r\n");
      out.write("  <article class=\"section_detail_select\" id=\"detail08\" name=\"detail\" style=\"display: none;\">\r\n");
      out.write("  <div class = \"detail_select\">\r\n");
      out.write("    <h3 class=\"detail_title\">문</h3>\r\n");
      out.write("<ul aria-label=\"문 선택 목록\" class=\"detail_item\">\r\n");
      out.write("    <li class=\"btn_line_detail\">\r\n");
      out.write("        <input type=\"radio\" id=\"group_door_item_0\" name=\"group_door_item\" value=\"전체교체\">\r\n");
      out.write("        <label for=\"group_door_item_0\">\r\n");
      out.write("            <span class=\"h4 select_detail__title\">전체교체</span>\r\n");
      out.write("            <p class=\"select_detail__desc\">문틀과문짝모두새로설치</p>\r\n");
      out.write("            <span class=\"expect_price\">326만원~</span>\r\n");
      out.write("        </label>\r\n");
      out.write("	<li class=\"btn_line_detail\">\r\n");
      out.write("        <input type=\"radio\" id=\"group_door_item_1\" name=\"group_door_item\" value=\"부분교체\">\r\n");
      out.write("        <label for=\"group_door_item_1\">\r\n");
      out.write("            <span class=\"h4 select_detail__title\">부분교체</span>\r\n");
      out.write("            <p class=\"select_detail__desc\">문틀과문짝부분교체</p>\r\n");
      out.write("            <span class=\"expect_price\">445만원~</span>\r\n");
      out.write("        </label>\r\n");
      out.write("        </li>\r\n");
      out.write("	<li class=\"btn_line_detail\">        \r\n");
      out.write("        <input type=\"radio\" id=\"group_door_item_2\" name=\"group_door_item\" value=\"필름\">\r\n");
      out.write("        <label for=\"group_door_item_2\">\r\n");
      out.write("            <span class=\"h4 select_detail__title\">필름</span>\r\n");
      out.write("            <p class=\"select_detail__desc\">문틀과문짝에시공가능</p>\r\n");
      out.write("            <span class=\"expect_price\">374만원~</span>\r\n");
      out.write("        </label>\r\n");
      out.write("        </li>\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("</article>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <div class=\"nextpage\">\r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("        <button class=\"button\" type=\"submit\">다음단계</button>\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      </form>\r\n");
      out.write("    </article>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function apply01_check() {\r\n");
      out.write("	if ($(':radio[name=\"est_use\"]:checked').length < 1) {\r\n");
      out.write("		alert('건물 유형을 선택해 주세요!');\r\n");
      out.write("		return false;\r\n");
      out.write("\r\n");
      out.write("	}\r\n");
      out.write("	if($('#cal1').val()==\"\" ||$('#cal1').val()==0){\r\n");
      out.write("		alert('평수를 입력해 주세요!');\r\n");
      out.write("		return false;\r\n");
      out.write("\r\n");
      out.write("	}\r\n");
      out.write("	if($('#cal2').val()==\"\" ||$('#cal2').val()==0){\r\n");
      out.write("		alert('평수를 입력해 주세요!');\r\n");
      out.write("		return false;\r\n");
      out.write("\r\n");
      out.write("	}\r\n");
      out.write("	if ($(':checkbox[name=\"check\"]:checked').length < 1) {\r\n");
      out.write("		alert('원하는 공간을 선택 주세요!');\r\n");
      out.write("		return false;\r\n");
      out.write("\r\n");
      out.write("	}\r\n");
      out.write("	SessionStorage_page01();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write(" ");
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
