/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-09-27 05:03:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.apply;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class applicationSheet4_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1663725906238L));
    _jspx_dependants.put("jar:file:/C:/20220607/프로젝트%20관련/teamproject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DoZip/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/apply_style_04.css\">\r\n");
      out.write("    <script src=\"./js/apply.js\" defer></script>\r\n");
      out.write("    <script src=\"./js/jquery.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("   <style>\r\n");
      out.write("   #p1 {\r\n");
      out.write("   	text-align: center;\r\n");
      out.write("   }\r\n");
      out.write("   #p1 b{\r\n");
      out.write("   color:#27562b\r\n");
      out.write("   	\r\n");
      out.write("   }\r\n");
      out.write("   #p1 b:hover{\r\n");
      out.write("   	color:#eb6703;\r\n");
      out.write("   	text-decoration: underline;\r\n");
      out.write("   }\r\n");
      out.write("   #msg2{\r\n");
      out.write("   	margin:0 auto;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write(".title {\r\n");
      out.write("    background-color: none;\r\n");
      out.write("    width: 600px;\r\n");
      out.write("    /* height: 100px; */\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("    margin-top: 18px;\r\n");
      out.write("  }\r\n");
      out.write("  .estimate_box{\r\n");
      out.write("    background-color: none;\r\n");
      out.write("    width: 600px;\r\n");
      out.write("    /* height: 500px; */\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("    margin-top: 18px;\r\n");
      out.write("  }\r\n");
      out.write("  .companies{\r\n");
      out.write("    background-color: rgb(248, 246, 246);\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  .title {\r\n");
      out.write("    display:flex;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("  }\r\n");
      out.write("  .title h3{\r\n");
      out.write("    color: #888;\r\n");
      out.write("    font-size: 28px;\r\n");
      out.write("    margin-top: 0;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  #p1 {\r\n");
      out.write("    font-weight: bolder;\r\n");
      out.write("    font-size: larger;\r\n");
      out.write("    margin-top: 50px;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  #p2{\r\n");
      out.write("    font-size: smaller;\r\n");
      out.write("    margin-top: 30px;\r\n");
      out.write("    margin-left: 30px;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  /*your_cost, proposed_cost*/\r\n");
      out.write("  .proposed_cost{\r\n");
      out.write("    display:flex;\r\n");
      out.write("  }\r\n");
      out.write("  .your_cost{\r\n");
      out.write("    display: flex;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  .estimate_box input[type=text]{\r\n");
      out.write("    font-size: large;\r\n");
      out.write("    margin: 10px 10px 0px 10px;  /*아래 오른쪽 위 왼쪽*/\r\n");
      out.write("    height: 35px;\r\n");
      out.write("    width: 450px;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  #li_01>img{\r\n");
      out.write("    width: 200px;\r\n");
      out.write("    height: 200px;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("/*다음 페이지 넘김 버튼*/\r\n");
      out.write(".nextpage{\r\n");
      out.write("  background-color: none;\r\n");
      out.write("  width: 600px;\r\n");
      out.write("  height: 100px;\r\n");
      out.write("  margin: 0 auto;\r\n");
      out.write("  margin-top: 18px;\r\n");
      out.write("}\r\n");
      out.write("#go-back{\r\n");
      out.write("  margin-top: 5%;\r\n");
      out.write("  width: 30%;\r\n");
      out.write("  height: 45px;\r\n");
      out.write("  border-radius: 10px;\r\n");
      out.write("  background-color: rgb(247, 226, 169);\r\n");
      out.write("  border:none;\r\n");
      out.write("  font: bolder;\r\n");
      out.write("}\r\n");
      out.write("#go-next{\r\n");
      out.write("  margin-top: 5%;\r\n");
      out.write("  width: 69%;\r\n");
      out.write("  height: 45px;\r\n");
      out.write("  border-radius: 10px;\r\n");
      out.write("  background-color: rgb(235, 103, 3);\r\n");
      out.write("  border:none;\r\n");
      out.write("  font: bolder;\r\n");
      out.write("  color: white;\r\n");
      out.write("}\r\n");
      out.write(".nextpage button:hover{\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("  \r\n");
      out.write("  #li_01{\r\n");
      out.write("    display: flex;\r\n");
      out.write("  }\r\n");
      out.write("#partners_info{\r\n");
      out.write("border:1px solid blue;\r\n");
      out.write("padding: 20px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   </style>\r\n");
      out.write("    \r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<div id = \"estimate_step04\">\r\n");
      out.write(" <section aria-label=\"주소 선택& 근처 업체\" class=\"youraddr\">\r\n");
      out.write("    <div class=\"title\">\r\n");
      out.write("        <h2>근처의 인테리어업체와 직접 연락할 수 있어요.</h2><h3>4/4</h3>\r\n");
      out.write(" 		\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"msg2\">\r\n");
      out.write("        <p id=\"p1\"><b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.mem_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</b> 님 근처에 <b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </b>개의 인테리어 업체가 있습니다.<br/>\r\n");
      out.write("        클릭해서 직접 상담해 볼 수 있어요.</p>\r\n");
      out.write("     </div>\r\n");
      out.write("    <div class = \"estimate_box\">\r\n");
      out.write("   <div class = \"companies\">\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("   			 \r\n");
      out.write("    \r\n");
      out.write("    ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("	\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    ");
      out.write("\r\n");
      out.write(" </div>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("        <div class=\"nextpage\">\r\n");
      out.write("          <button class=\"button\" id=\"go-back\" onclick=\"location.href='estimate_apply3.do'\">이전</button>\r\n");
      out.write("          <button class=\"button\" id=\"go-next\" onclick=\"location.href='estimate_apply5.do'\">다음</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write(" </section>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write(" ");
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /apply/applicationSheet4.jsp(159,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("p");
      // /apply/applicationSheet4.jsp(159,4) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("    \r\n");
            out.write("    			<div id=partners_info>\r\n");
            out.write("    			<input id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.businessName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" type=\"checkbox\"> <label for=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.businessName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write(' ');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.businessName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("	</label><br>			\r\n");
            out.write(" 				전화번호 : ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.pTel }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("<br>\r\n");
            out.write(" 				주소 :");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.pAddress}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("<br>\r\n");
            out.write(" 				사업자 번호 : ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.business_num }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write(" 				\r\n");
            out.write(" 				</div>\r\n");
            out.write(" 				\r\n");
            out.write(" 			");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
