/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-09-28 10:10:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.review;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class review_005fmain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"review_wrap\">\r\n");
      out.write("	<br/>\r\n");
      out.write("	<!-- 드롭다운 버튼 -->\r\n");
      out.write("		<div class = \"dropdown\">\r\n");
      out.write("			<select name=\"d1\" class=\"dd_group\" style=\"margin-left:30px;\">\r\n");
      out.write("				<option selected>주거유형</option>\r\n");
      out.write("				<option value=\"아파트\">아파트</option>\r\n");
      out.write("				<option value=\"빌라\">빌라</option>\r\n");
      out.write("				<option value=\"주택\">주택</option>\r\n");
      out.write("				<option value=\"오피스텔\">오피스텔</option>\r\n");
      out.write("			</select>\r\n");
      out.write("			<select name=\"d2\" class=\"dd_group\">\r\n");
      out.write("				<option selected>상업유형</option>\r\n");
      out.write("				<option value=\"카페/식당\">카페/식당</option>\r\n");
      out.write("				<option value=\"상가/매장\">상가/매장</option>\r\n");
      out.write("				<option value=\"학원/교육\">학원/교육</option>\r\n");
      out.write("				<option value=\"사무실\">사무실</option>\r\n");
      out.write("				<option value=\"숙박/병원\">숙박/병원</option>\r\n");
      out.write("				<option value = \"간판\">간판</option>\r\n");
      out.write("				<option value = \"기타\">기타</option>\r\n");
      out.write("			</select>\r\n");
      out.write("			<select name=\"d3\" class=\"dd_group\">\r\n");
      out.write("				<option selected>스타일</option>\r\n");
      out.write("				<option value=\"모던\">모던</option>\r\n");
      out.write("				<option value=\"심플/미니멀\">심플/미니멀</option>\r\n");
      out.write("				<option value=\"내추럴\">내추럴</option>\r\n");
      out.write("				<option value=\"빈티지\">빈티지</option>\r\n");
      out.write("				<option value=\"럭셔리\">럭셔리</option>\r\n");
      out.write("			</select>\r\n");
      out.write("			<select name=\"d4\" class=\"dd_group\">\r\n");
      out.write("				<option selected>비용</option>\r\n");
      out.write("				<option value=\"1000만원 이하\">1000만원 이하</option>\r\n");
      out.write("				<option value=\"1000만원대\">1000만원대</option>\r\n");
      out.write("				<option value=\"2000만원대\">2000만원대</option>\r\n");
      out.write("				<option value=\"3000만원대\">3000만원대</option>\r\n");
      out.write("				<option value=\"4000만원대\">4000만원대</option>\r\n");
      out.write("				<option value=\"5000만원대\">5000만원대</option>\r\n");
      out.write("				<option value=\"6000만원 이상\">6000만원 이상</option>\r\n");
      out.write("			</select>\r\n");
      out.write("			<select name=\"d5\" class=\"dd_group\">\r\n");
      out.write("				<option selected>평수</option>\r\n");
      out.write("				<option value=\"10평대\">10평대</option>\r\n");
      out.write("				<option value=\"20평대\">20평대</option>\r\n");
      out.write("				<option value=\"30평대\">30평대</option>\r\n");
      out.write("				<option value=\"50평대\">50평대</option>\r\n");
      out.write("				<option value=\"60평대 이상\">60평대 이상</option>\r\n");
      out.write("			</select>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("		<div class=\"review_write\">\r\n");
      out.write("			<button type=\"button\" onclick=\"location.href='review_write.do'\">후기 작성하기 >></button>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<!-- part1  -->\r\n");
      out.write("		<div class=\"part1\">\r\n");
      out.write("			<span id=\"part1_title\">BEST 후기</span>\r\n");
      out.write("			<span id=\"part1_count\">총 122개의 고객후기</span>\r\n");
      out.write("			<div class=\"big_review\">\r\n");
      out.write("				<img id=\"big_img\" src=\"/DoZip/images/ex01.png\" />\r\n");
      out.write("				<div class=\"big_review_cont\">\r\n");
      out.write("					<p id=\"review_title\">글제목</p>\r\n");
      out.write("					<p id=\"review_cont\">집닥을 통해 여러군데 견적을 받았어요. 그 중에 여기가 견적서도 빨리 보내주고 제가 원하는 가격에 최대한 맞춰서 인테리어를 도와주셨어요! 요즘 인테리어 사기가 많아서 고민하고 걱정했는데 확실하게 일 처리 해주시고 전기부터 소방까지 꼼꼼하게 챙겨주셨어요. 벽지나 타일을 고르는데 고민이 많은데 추천도 잘 해주시고 지금도 대 만족 하고 있습니다</p>\r\n");
      out.write("					<p id=\"review_tag\"><button>주거유형</button><button>스타일</button><button>평수</button></p>\r\n");
      out.write("					<p id=\"review_info\">글쓴이 고객님 | 2022.04.23</p>\r\n");
      out.write("					<div id=\"revie_go_box\"><a href=\"review_detail.do\" id=\"revie_go\">해당 리뷰보러 가기 >> </a></div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	\r\n");
      out.write("		<!-- part2 -->\r\n");
      out.write("		<div class=\"part2\">\r\n");
      out.write("		<div id=\"part5_area\">\r\n");
      out.write("			<div class=\"part5_inner\">\r\n");
      out.write("				<div><a class=\"part5_img\" href=\"review_detail.do\">\r\n");
      out.write("					<img src=\"/DoZip/images/review1.jpg\"/>\r\n");
      out.write("				</a></div>\r\n");
      out.write("				<div class=\"part5_title\"><p>깔끔한 주방 인테리어</p></div>\r\n");
      out.write("				<div class=\"part5_cont\">\r\n");
      out.write("					<p>싱크대 상판을 세라믹으로 하고 화장대의 상판과 수납장 하나의 상판도 세라믹으로 해서 효율적으로 세라믹을 사용할 수 있어서 만족합니다. 인조대리석보다 비싸지만 아주 만족합니다.</p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<p></p>					\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"part5_inner\">\r\n");
      out.write("				<div><a class=\"part5_img\" href=\"review_detail.do\">\r\n");
      out.write("					<img src=\"/DoZip/images/review2.jpg\"/>\r\n");
      out.write("				</a></div>\r\n");
      out.write("				<div class=\"part5_title\"><p>아늑하고 분위기 있는 침실</p></div>\r\n");
      out.write("				<div class=\"part5_cont\">\r\n");
      out.write("					<p>편안하고 분위기 있는 침실을 원했어요. 업체와 여러번의 이야기를 통해 제가 원하는 느낌을 찾을 수 잇었어요. 소통이 원활해서 큰 스트레스를 받지 않고 공사를 진행할 수 있었습니다. 군더더기 없이 침실공간을 만들고 싶었는데 제가 원하던대로 잘 나온거 같아요.</p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<p></p>					\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"part5_inner\">\r\n");
      out.write("				<div><a class=\"part5_img\" href=\"review_detail.do\">\r\n");
      out.write("					<img src=\"/DoZip/images/review3.jpg\"/>\r\n");
      out.write("				</a></div>\r\n");
      out.write("				<div class=\"part5_title\"><p>작업을 위한 작업실 공사</p></div>\r\n");
      out.write("				<div class=\"part5_cont\">\r\n");
      out.write("					<p>프리랜서로 일하고 있는데, 이번에 두집을 통해 작업실 공사를 맡겨봤어요. 어떻게 해야할지 몰랐는데 전문가분들이 여러가지 시안을 보여주시면서 선택할 수 있도록 도와주셔서 더 좋은 결과물이 나온거 같아요. 만족합니다.</p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<p></p>					\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>	\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"part3\">\r\n");
      out.write("		<button id=\"more\" type=\"button\">더 보기</button>\r\n");
      out.write("	</div>\r\n");
      out.write("		\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
