/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-09-30 01:31:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.estimate_005frequest;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class bid_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css\" integrity=\"sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div class=\"request_page\">\r\n");
      out.write("			<form method=\"post\" action=\"bid_board_list.do\">\r\n");
      out.write("			<div class=\"request_spot\">\r\n");
      out.write("				<h2 class=\"item_title\">입찰의뢰</h2>\r\n");
      out.write("						<div class=\"search_box\">\r\n");
      out.write("					    <input class=\"search-txt\" type=\"text\" placeholder=\"검색어를 입력해 주세요\">\r\n");
      out.write("					    <button class=\"search-btn\" type=\"submit\">\r\n");
      out.write("					    	<img src=\"./images/search.png\" width=\"20px\" height=\"20px\">\r\n");
      out.write("					    </button>\r\n");
      out.write("						</div>\r\n");
      out.write("					<div class=\"my_bid_icon\">\r\n");
      out.write("						<a href=\"./my_bid.do\"\r\n");
      out.write("							class=\"to_my_bid\" target=\"_blank\"><img src=\"./images/bid_list.png\" width=\"55px\" height=\"55px\"></a>\r\n");
      out.write("					</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"request_list_container\">\r\n");
      out.write("				<div class=\"request_list\">\r\n");
      out.write("					<div class=\"request_list_top\">\r\n");
      out.write("						<input type=\"checkbox\" id=\"filter\"> \r\n");
      out.write("							<label for=\"filter\" class=\"filter\">완료 의뢰 건 제외</label> \r\n");
      out.write("						<div class=\"request_list_top_right\">\r\n");
      out.write("							<select class=\"fd_search_filter\" id=\"pr_order\" data-self=\"pr_order\" data-type=\"simple\">\r\n");
      out.write("								<option value=\"recent\">최신 등록 순</option>\r\n");
      out.write("								<option value=\"due_date\">마감 임박 순</option>\r\n");
      out.write("								<option value=\"request_budget\">예산 규모 순</option>\r\n");
      out.write("							</select>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"request_list_card\">\r\n");
      out.write("						<div class=\"request_list_item01\">\r\n");
      out.write("							<p class=\"request_day\">\r\n");
      out.write("								모집중 D-<span>2</span>\r\n");
      out.write("							</p>\r\n");
      out.write("							<p class=\"label_badge\">\r\n");
      out.write("								<span class=\"label_val1\">사무실</span>\r\n");
      out.write("								<span class=\"label_val2\">도배/바닥/욕실 공사</span>\r\n");
      out.write("							</p>\r\n");
      out.write("							<p class=\"request_title\">\r\n");
      out.write("								<a href=\"./bid_detail.jsp\">목동 사무실 원상복구 견적 문의</a>\r\n");
      out.write("							</p>\r\n");
      out.write("							<div class=\"request_desc_div\">\r\n");
      out.write("								<p class=\"request_desc\">\r\n");
      out.write("								1. 이사예정이 7/19(화)이라 18일까지는 완료가 되어야 합니다.(기존3층에 임대사무실 사용 후 9층 매매완료하여 이사) 이사예정인 사무실은 15일 오전중에 공실이 됩니다.</br>\r\n");
      out.write("								2. 바닥재은 어두운계열로, 벽면은 합판이 덧대어져있는것 같은데 페이트 혹은 들뜨지않게 마감처리하여 깔끔하게 될 수 있도록 페인트 혹은 벽지 두가지 생각하고 있습니다.\r\n");
      out.write("								3. 전등갓이 불량하여 변경이 이뤄져야합니다.\r\n");
      out.write("								4. 외부시트지 디자인작업이 필요합니다.\r\n");
      out.write("								</p>\r\n");
      out.write("							</div>\r\n");
      out.write("								<ul class=\"request_info\">\r\n");
      out.write("									<li class=\"info\">\r\n");
      out.write("										<p class=\"request_info_tit\">희망 예산</p>\r\n");
      out.write("										<p class=\"request_info_val\">\r\n");
      out.write("											<span><b>5000000</b></span>\r\n");
      out.write("										</p>\r\n");
      out.write("									</li>\r\n");
      out.write("									<li class=\"info\">\r\n");
      out.write("										<p class=\"request_info_tit\">모집 마감일</p>\r\n");
      out.write("										<p class=\"request_info_val\">\r\n");
      out.write("											<span><b>2022.08.31</b></span>\r\n");
      out.write("										</p>\r\n");
      out.write("									</li>\r\n");
      out.write("									<li class=\"info\">\r\n");
      out.write("										<p class=\"request_info_tit\">희망 시공시작일</p>\r\n");
      out.write("										<p class=\"request_info_val\">\r\n");
      out.write("											<span><b>2022.09.01</b></span>\r\n");
      out.write("										</p>\r\n");
      out.write("									</li>\r\n");
      out.write("									<li class=\"info\">\r\n");
      out.write("										<p class=\"request_info_tit\">희망 시공종료일</p>\r\n");
      out.write("										<p class=\"request_info_val\">\r\n");
      out.write("											<span><b>2022.09.12</b></span>\r\n");
      out.write("										</p>\r\n");
      out.write("									</li>\r\n");
      out.write("								</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"request_list_item02\">\r\n");
      out.write("							<ul class=\"company_profile\">\r\n");
      out.write("								<li class=\"info2\">\r\n");
      out.write("									<p class=\"key\">시공규모</p>\r\n");
      out.write("									<p class=\"val\"><b>21.96m<sup>2</sup>(10평)</b></p></li>\r\n");
      out.write("								<li class=\"info2\">\r\n");
      out.write("									<p class=\"key\">시공주소</p>\r\n");
      out.write("									<p class=\"val\"><b>경기 성남시</b></p></li>\r\n");
      out.write("								<li class=\"info2\">\r\n");
      out.write("									<p class=\"key\">참여 파트너수</p>\r\n");
      out.write("									<p class=\"val\"><b>3</b></p></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("							<div class=\"bid_detail\">\r\n");
      out.write("								<a href=\"./bid_detail.do\" class=\"btn-d-view\" >자세히 보기</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>						\r\n");
      out.write("					</div></br>\r\n");
      out.write("					\r\n");
      out.write("					<div class=\"request_list_card\">\r\n");
      out.write("						<div class=\"request_list_item01\">\r\n");
      out.write("							<p class=\"request_day\">\r\n");
      out.write("								모집중 D-<span>2</span>\r\n");
      out.write("							</p>\r\n");
      out.write("							<p class=\"label_badge\">\r\n");
      out.write("								<span class=\"label_val1\">사무실</span>\r\n");
      out.write("								<span class=\"label_val2\">도배/바닥/욕실 공사</span>\r\n");
      out.write("							</p>\r\n");
      out.write("							<p class=\"request_title\">\r\n");
      out.write("								<a href=\"./bid_detail.jsp\">목동 사무실 원상복구 견적 문의</a>\r\n");
      out.write("							</p>\r\n");
      out.write("							<div class=\"request_desc_div\">\r\n");
      out.write("								<p class=\"request_desc\">\r\n");
      out.write("								1. 이사예정이 7/19(화)이라 18일까지는 완료가 되어야 합니다.(기존3층에 임대사무실 사용 후 9층 매매완료하여 이사) 이사예정인 사무실은 15일 오전중에 공실이 됩니다.</br>\r\n");
      out.write("								2. 바닥재은 어두운계열로, 벽면은 합판이 덧대어져있는것 같은데 페이트 혹은 들뜨지않게 마감처리하여 깔끔하게 될 수 있도록 페인트 혹은 벽지 두가지 생각하고 있습니다.\r\n");
      out.write("								3. 전등갓이 불량하여 변경이 이뤄져야합니다.\r\n");
      out.write("								4. 외부시트지 디자인작업이 필요합니다.\r\n");
      out.write("								</p>\r\n");
      out.write("							</div>\r\n");
      out.write("								<ul class=\"request_info\">\r\n");
      out.write("									<li class=\"info\">\r\n");
      out.write("										<p class=\"request_info_tit\">희망 예산</p>\r\n");
      out.write("										<p class=\"request_info_val\">\r\n");
      out.write("											<span><b>5000000</b></span>\r\n");
      out.write("										</p>\r\n");
      out.write("									</li>\r\n");
      out.write("									<li class=\"info\">\r\n");
      out.write("										<p class=\"request_info_tit\">모집 마감일</p>\r\n");
      out.write("										<p class=\"request_info_val\">\r\n");
      out.write("											<span><b>2022.08.31</b></span>\r\n");
      out.write("										</p>\r\n");
      out.write("									</li>\r\n");
      out.write("									<li class=\"info\">\r\n");
      out.write("										<p class=\"request_info_tit\">희망 시공시작일</p>\r\n");
      out.write("										<p class=\"request_info_val\">\r\n");
      out.write("											<span><b>2022.09.01</b></span>\r\n");
      out.write("										</p>\r\n");
      out.write("									</li>\r\n");
      out.write("									<li class=\"info\">\r\n");
      out.write("										<p class=\"request_info_tit\">희망 시공종료일</p>\r\n");
      out.write("										<p class=\"request_info_val\">\r\n");
      out.write("											<span><b>2022.09.12</b></span>\r\n");
      out.write("										</p>\r\n");
      out.write("									</li>\r\n");
      out.write("								</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"request_list_item02\">\r\n");
      out.write("							<ul class=\"company_profile\">\r\n");
      out.write("								<li class=\"info2\">\r\n");
      out.write("									<p class=\"key\">시공규모</p>\r\n");
      out.write("									<p class=\"val\"><b>21.96m<sup>2</sup>(10평)</b></p></li>\r\n");
      out.write("								<li class=\"info2\">\r\n");
      out.write("									<p class=\"key\">시공주소</p>\r\n");
      out.write("									<p class=\"val\"><b>경기 성남시</b></p></li>\r\n");
      out.write("								<li class=\"info2\">\r\n");
      out.write("									<p class=\"key\">참여 파트너수</p>\r\n");
      out.write("									<p class=\"val\"><b>3</b></p></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("							<div class=\"bid_detail\">\r\n");
      out.write("								<a href=\"./bid_detail.do\" class=\"btn-d-view\" >자세히 보기</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>						\r\n");
      out.write("					</div></br>\r\n");
      out.write("					\r\n");
      out.write("					<div class=\"request_list_card\">\r\n");
      out.write("						<div class=\"request_list_item01\">\r\n");
      out.write("							<p class=\"request_day\">\r\n");
      out.write("								모집중 D-<span>2</span>\r\n");
      out.write("							</p>\r\n");
      out.write("							<p class=\"label_badge\">\r\n");
      out.write("								<span class=\"label_val1\">사무실</span>\r\n");
      out.write("								<span class=\"label_val2\">도배/바닥/욕실 공사</span>\r\n");
      out.write("							</p>\r\n");
      out.write("							<p class=\"request_title\">\r\n");
      out.write("								<a href=\"./bid_detail.jsp\">목동 사무실 원상복구 견적 문의</a>\r\n");
      out.write("							</p>\r\n");
      out.write("							<div class=\"request_desc_div\">\r\n");
      out.write("								<p class=\"request_desc\">\r\n");
      out.write("								1. 이사예정이 7/19(화)이라 18일까지는 완료가 되어야 합니다.(기존3층에 임대사무실 사용 후 9층 매매완료하여 이사) 이사예정인 사무실은 15일 오전중에 공실이 됩니다.</br>\r\n");
      out.write("								2. 바닥재은 어두운계열로, 벽면은 합판이 덧대어져있는것 같은데 페이트 혹은 들뜨지않게 마감처리하여 깔끔하게 될 수 있도록 페인트 혹은 벽지 두가지 생각하고 있습니다.\r\n");
      out.write("								3. 전등갓이 불량하여 변경이 이뤄져야합니다.\r\n");
      out.write("								4. 외부시트지 디자인작업이 필요합니다.\r\n");
      out.write("								</p>\r\n");
      out.write("							</div>\r\n");
      out.write("								<ul class=\"request_info\">\r\n");
      out.write("									<li class=\"info\">\r\n");
      out.write("										<p class=\"request_info_tit\">희망 예산</p>\r\n");
      out.write("										<p class=\"request_info_val\">\r\n");
      out.write("											<span><b>5000000</b></span>\r\n");
      out.write("										</p>\r\n");
      out.write("									</li>\r\n");
      out.write("									<li class=\"info\">\r\n");
      out.write("										<p class=\"request_info_tit\">모집 마감일</p>\r\n");
      out.write("										<p class=\"request_info_val\">\r\n");
      out.write("											<span><b>2022.08.31</b></span>\r\n");
      out.write("										</p>\r\n");
      out.write("									</li>\r\n");
      out.write("									<li class=\"info\">\r\n");
      out.write("										<p class=\"request_info_tit\">희망 시공시작일</p>\r\n");
      out.write("										<p class=\"request_info_val\">\r\n");
      out.write("											<span><b>2022.09.01</b></span>\r\n");
      out.write("										</p>\r\n");
      out.write("									</li>\r\n");
      out.write("									<li class=\"info\">\r\n");
      out.write("										<p class=\"request_info_tit\">희망 시공종료일</p>\r\n");
      out.write("										<p class=\"request_info_val\">\r\n");
      out.write("											<span><b>2022.09.12</b></span>\r\n");
      out.write("										</p>\r\n");
      out.write("									</li>\r\n");
      out.write("								</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"request_list_item02\">\r\n");
      out.write("							<ul class=\"company_profile\">\r\n");
      out.write("								<li class=\"info2\">\r\n");
      out.write("									<p class=\"key\">시공규모</p>\r\n");
      out.write("									<p class=\"val\"><b>21.96m<sup>2</sup>(10평)</b></p></li>\r\n");
      out.write("								<li class=\"info2\">\r\n");
      out.write("									<p class=\"key\">시공주소</p>\r\n");
      out.write("									<p class=\"val\"><b>경기 성남시</b></p></li>\r\n");
      out.write("								<li class=\"info2\">\r\n");
      out.write("									<p class=\"key\">참여 파트너수</p>\r\n");
      out.write("									<p class=\"val\"><b>3</b></p></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("							<div class=\"bid_detail\">\r\n");
      out.write("								<a href=\"./bid_detail.do\" class=\"btn-d-view\" >자세히 보기</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>						\r\n");
      out.write("					</div></br>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("				<!--  \r\n");
      out.write("				<div class=\"bottom-btn-wrap\">\r\n");
      out.write("					<button type=\"button\" class=\"more_button\"><img src=\"../images/more_plus.png\"></br><span>더보기</span></button>\r\n");
      out.write("				</div> -->\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
