/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-09-28 10:24:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.partners.dao.PartnersDAO;
import com.partners.dto.PartnersDTO;

public final class data_005fmanage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.partners.dao.PartnersDAO");
    _jspx_imports_classes.add("com.partners.dto.PartnersDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	
	/* String [] value= request.getParameterValues("pService");
	for(String val: value){
		out.print(val+"<br>");
	} */

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function selectAll1(selectAll)  {\r\n");
      out.write("	  const checkboxes \r\n");
      out.write("	       = document.getElementsByName('pRes_build_type');\r\n");
      out.write("	  \r\n");
      out.write("	  checkboxes.forEach((checkbox) => {\r\n");
      out.write("	    checkbox.checked = selectAll.checked;\r\n");
      out.write("	  })\r\n");
      out.write("	}\r\n");
      out.write("function selectAll2(selectAll)  {\r\n");
      out.write("	  const checkboxes \r\n");
      out.write("	       = document.getElementsByName('pRes_space_type');\r\n");
      out.write("	  \r\n");
      out.write("	  checkboxes.forEach((checkbox) => {\r\n");
      out.write("	    checkbox.checked = selectAll.checked;\r\n");
      out.write("	  })\r\n");
      out.write("	}\r\n");
      out.write("function selectAll3(selectAll)  {\r\n");
      out.write("  const checkboxes \r\n");
      out.write("       = document.getElementsByName('pCom_build_type');\r\n");
      out.write("  \r\n");
      out.write("  checkboxes.forEach((checkbox) => {\r\n");
      out.write("    checkbox.checked = selectAll.checked;\r\n");
      out.write("  })\r\n");
      out.write("}\r\n");
      out.write("function selectAll4(selectAll)  {\r\n");
      out.write("  const checkboxes \r\n");
      out.write("       = document.getElementsByName('pCom_space_type');\r\n");
      out.write("  \r\n");
      out.write("  checkboxes.forEach((checkbox) => {\r\n");
      out.write("    checkbox.checked = selectAll.checked;\r\n");
      out.write("  })\r\n");
      out.write("}\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("  <article>\r\n");
      out.write("   <div>\r\n");
      out.write("	  	<div class=\"request_spot\">\r\n");
      out.write("	  		<div class=\"request_color\">\r\n");
      out.write("		    <h2 class=\"item_title\" >내 정보관리</h2>\r\n");
      out.write("		    \r\n");
      out.write("			  	<div class=\"item_tab_box\" >\r\n");
      out.write("			  		<div role=\"tablist\" class=\"item_tab_inbox\" id=\"business-link\">\r\n");
      out.write("			  			<div id=\"tab1\"><a href=\"#business-link\" class=\"tab-link\" >사업자 정보</a></div>\r\n");
      out.write("			  			<div id=\"tab2\"><a href=\"#additional-link\" class=\"tab-link\">부가 정보</a></div>\r\n");
      out.write("			  			<div id=\"tab3\"><a href=\"#pHomepg\" class=\"tab-link\">선호 시공정보</a></div>\r\n");
      out.write("			  			<div id=\"tab4\"><a href=\"#representative-link\" class=\"tab-link\">담당자 정보</a></div>\r\n");
      out.write("			  			<div id=\"tab5\"><a href=\"#payment-link\" class=\"tab-link\">정산 정보</a></div>  			\r\n");
      out.write("			  		</div>\r\n");
      out.write("			  	</div>\r\n");
      out.write("		  	</div>\r\n");
      out.write("  		</div>    \r\n");
      out.write("    <div class=\"all_information\">\r\n");
      out.write("		<form method=\"post\" action=\"data_manage_edit_ok.do\">\r\n");
      out.write("			<fieldset id=\"business\">\r\n");
      out.write("				<legend>\r\n");
      out.write("					<b>사업자 정보</b>\r\n");
      out.write("				</legend>\r\n");
      out.write("				<div class=\"business-01\">\r\n");
      out.write("					<div class=\"business-01-1\">\r\n");
      out.write("						<label><b>사업자등록번호</b></label><br />\r\n");
      out.write("						<div>\r\n");
      out.write("							<input type=\"text\" id=\"business_num\" name=\"business_num\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.business_num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" size=\"30\"> \r\n");
      out.write("							<!--  <input type=\"text\" id=\"business_num\" name=\"business_num\" size=\"5\">\r\n");
      out.write("							<input type=\"text\" id=\"business_num\" name=\"business_num\" size=\"5\"> -->\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<br />\r\n");
      out.write("					<div class=\"business-01-2\">\r\n");
      out.write("						<label><b>상호</b></label><br />\r\n");
      out.write("						<div>\r\n");
      out.write("							<input type=\"text\" id=\"businessName\" name=\"businessName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.businessName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" size=\"30\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<br />\r\n");
      out.write("				<div class=\"business-03\">\r\n");
      out.write("					<label><b>대표자 이름</b></label><br />\r\n");
      out.write("					<div>\r\n");
      out.write("						<input type=\"text\" id=\"pName\" name=\"pName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.pName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" size=\"30\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<br />\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"business-04\">\r\n");
      out.write("					<label><b>대표자 연락처</b></label><br />\r\n");
      out.write("					<div>\r\n");
      out.write("						<input type=\"text\" id=\"pTel\" name=\"pTel\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.pTel}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" size=\"30\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<br />\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"business-05\" id=\"additional-link\">\r\n");
      out.write("					<label><b>영업장 주소</b></label><br />\r\n");
      out.write("					<div>\r\n");
      out.write("						<!--  <input type=\"text\" size=\"5\" disabled=\"true\"> \r\n");
      out.write("						<input type=\"text\" size=\"10\" disabled=\"true\"> \r\n");
      out.write("						<button type=\"button\">변경</button> -->\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<input type=\"text\"  id=\"pAddress\" name=\"pAddress\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.pAddress}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" size=\"30\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<br />\r\n");
      out.write("				</div>\r\n");
      out.write("			</fieldset>\r\n");
      out.write("\r\n");
      out.write("			<fieldset id=\"additional\">\r\n");
      out.write("				<legend>\r\n");
      out.write("					<b>부가 정보</b>\r\n");
      out.write("				</legend>\r\n");
      out.write("				<div class=\"additional-01\">\r\n");
      out.write("					<label><b>전문가 한마디</b></label><br />\r\n");
      out.write("						<textarea id=\"pShortstate\" name=\"pShortstate\" autocomplete=\"off\"\r\n");
      out.write("							placeholder=\"(EX. 따듯함이 느껴지는 원목과 화이트 컬러의 내추럴 스타일, 33평 아파트 인테리어입니다.)\" rows=\"5\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ps.pShortstate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("					<span class=\"text\">0/2000</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"additional-02\">\r\n");
      out.write("					<label class=\"upload_image_title\"><b>대표 인테리어 이미지</b></label><br />\r\n");
      out.write("					<div class=\"upload_image_size\">(권장 이미지 사이즈 750 x 600)</div>\r\n");
      out.write("					<div tabindex=\"0\" class=\"upload_image\" >\r\n");
      out.write("						<label for=\"pInt_img\" class=\"upload_lbl\">  <!-- label for과 input id가 같아야 적용됨 -->\r\n");
      out.write("							<img src=\"./images/upload_plus.png\" width=\"40px\" height=\"40px\">\r\n");
      out.write("						</label>\r\n");
      out.write("						<input type=\"file\" id=\"pInt_img\" name=\"pInt_img\" accept=\"image/*\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<br />\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"additional-03\">\r\n");
      out.write("					<label class=\"upload_image_title\"><b>파트너스 로고 이미지</b></label><br />\r\n");
      out.write("					<div class=\"upload_image_size\">(권장 이미지 사이즈 300 x 300)</div>\r\n");
      out.write("					<div tabindex=\"0\" class=\"upload_image\" >\r\n");
      out.write("						<label for=\"pComp_logo\" class=\"upload_lbl\">\r\n");
      out.write("							<img src=\"./images/upload_plus.png\" width=\"40px\" height=\"40px\">\r\n");
      out.write("						</label>\r\n");
      out.write("						<input type=\"file\" id=\"pComp_logo\" name=\"pComp_logo\" accept=\"image/*\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<br />\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"additional-04\">\r\n");
      out.write("					<label><b>제공 서비스</b></label><br />\r\n");
      out.write("					<div>제공하는 서비스를 모두 선택해 주세요.</div>\r\n");
      out.write("			\r\n");
      out.write("						<label for=\"service1\" class=\"lbl-checkbox\"> <input type=\"checkbox\" name=\"pService\" id=\"service1\" value=\"3D도면\">3D도면</label>\r\n");
      out.write("						<label for=\"service2\" class=\"lbl-checkbox\"> <input type=\"checkbox\" name=\"pService\" id=\"service2\" value=\"일반도면\">일반도면</label>\r\n");
      out.write("						<label for=\"service3\" class=\"lbl-checkbox\"> <input type=\"checkbox\" name=\"pService\" id=\"service3\" value=\"카드결제\">카드결제</label>\r\n");
      out.write("						<label for=\"service4\" class=\"lbl-checkbox\"> <input type=\"checkbox\" name=\"pService\" id=\"service4\" value=\"쇼룸\">쇼룸</label>\r\n");
      out.write("						<label for=\"service5\" class=\"lbl-checkbox\"> <input type=\"checkbox\" name=\"pService\" id=\"service5\" value=\"정부지원사업\">정부지원사업</label></br>\r\n");
      out.write("						<label for=\"service6\" class=\"lbl-checkbox-disabled\"><input type=\"checkbox\" name=\"pService\" id=\"service6\" value=\"두집예치제\">두집예치제</label>\r\n");
      out.write("						<label class=\"deposit_label\">예치금</label> <input type=\"text\" id=\"deposit_money\" name=\"pBalance\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ps.pBalance}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" >\r\n");
      out.write("						<p id=\"red\">* 두집예치제는 두집(****-****)으로 추가 문의주세요.</p>\r\n");
      out.write("					<div class=\"current-service\">\r\n");
      out.write("						<label>현재 제공하는 서비스</label>\r\n");
      out.write("					\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("					\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"additional-05\">\r\n");
      out.write("					<label><b>홈페이지</b></label><br />\r\n");
      out.write("					<textarea class=\"homepage\" autocomplete=\"off\" name=\"pHomepg\" id=\"pHomepg\" placeholder=\"홈페이지를 입력하세요\" rows=\"3\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ps.pHomepg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("				</div>\r\n");
      out.write("				<br />\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				<!--  \r\n");
      out.write("				<div class=\"additional-06\">\r\n");
      out.write("					<label><b>업체사진(실내)</b></label><br />\r\n");
      out.write("					<div tabindex=\"0\" class=\"upload_image2\" >\r\n");
      out.write("						<label for=\"choosefile\" class=\"upload_lbl2\">\r\n");
      out.write("							<img src=\"../images/upload_plus.png\" width=\"40px\" height=\"40px\">\r\n");
      out.write("						</label>\r\n");
      out.write("						<input type=\"file\" id=\"choosefile\" name=\"file\" accept=\"image/*\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<br />\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"additional-07\">\r\n");
      out.write("					<label><b>업체사진(실외)</b></label><br />\r\n");
      out.write("					<div tabindex=\"0\" class=\"upload_image2\" >\r\n");
      out.write("						<label for=\"choosefile\" class=\"upload_lbl2\">\r\n");
      out.write("							<img src=\"../images/upload_plus.png\" width=\"40px\" height=\"40px\">\r\n");
      out.write("						</label>\r\n");
      out.write("						<input type=\"file\" id=\"choosefile\" name=\"file\" accept=\"image/*\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				-->\r\n");
      out.write("				\r\n");
      out.write("			</fieldset>\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("			<fieldset id=\"preference\">\r\n");
      out.write("				<legend>\r\n");
      out.write("					<b>선호 시공정보</b>\r\n");
      out.write("				</legend>\r\n");
      out.write("				<div>\r\n");
      out.write("					<span><b>주거공간</b></span> <span>▼</span>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=''>\r\n");
      out.write("					<div>\r\n");
      out.write("						<b><span id=\"red\">*</span></b><span> <b>건물 유형(최소 2개 이상)</b></span>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"residence\">\r\n");
      out.write("							<label for=\"res_build_all\" class=\"lbl-checkbox\"> <input type=\"checkbox\" name=\"pRes_build_type_all\" id=\"res_build_all\" value=\"\" onclick=\"selectAll1(this)\"></input> 전체</label><br />\r\n");
      out.write("						<div>\r\n");
      out.write("							<label for=\"res_build01\" class=\"lbl-checkbox\"> <input type=\"checkbox\" name=\"pRes_build_type\" id=\"res_build01\" value=\"아파트\">아파트</input></label>\r\n");
      out.write("							<label for=\"res_build02\" class=\"lbl-checkbox\"> <input type=\"checkbox\" name=\"pRes_build_type\" id=\"res_build02\" value=\"빌라\">빌라</input></label>\r\n");
      out.write("							<label for=\"res_build03\" class=\"lbl-checkbox\"> <input type=\"checkbox\" name=\"pRes_build_type\" id=\"res_build03\" value=\"주택\">주택</input></label>\r\n");
      out.write("							<label for=\"res_build04\" class=\"lbl-checkbox\"> <input type=\"checkbox\"name=\"pRes_build_type\" id=\"res_build04\" value=\"오피스텔\">오피스텔</input></label>\r\n");
      out.write("						</div> <!-- label의 for와 input의 id가 같아야 label값 눌러도 선택됨 -->\r\n");
      out.write("					</div>\r\n");
      out.write("					<br />\r\n");
      out.write("\r\n");
      out.write("					<div>\r\n");
      out.write("						<b><span id=\"red\">*</span></b><span> <b>가능한 공간</b></span>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"residence\" >\r\n");
      out.write("						<label for=\"res_space_all\" class=\"lbl-checkbox\"> <input type=\"checkbox\" name=\"pRes_space_type_all\" id=\"res_space_all\" value=\"\" onclick=\"selectAll2(this)\"></input>전체</label><br />\r\n");
      out.write("						<!-- <h5 class=\"sigong\">시공</h5>  -->\r\n");
      out.write("						<div>\r\n");
      out.write("							<!--  <input type=\"checkbox\" id=\"wall\" name=\"check\" data-name=\"도배/벽\"  class =\"checkbox\"/> -->\r\n");
      out.write("							<label for=\"res_space01\" class=\"lbl-checkbox\"> <input type=\"checkbox\" name=\"pRes_space_type\" id=\"res_space01\" value=\"도배/벽\">도배/벽</input></label>\r\n");
      out.write("							<label for=\"res_space02\" class=\"lbl-checkbox\"> <input type=\"checkbox\" name=\"pRes_space_type\" id=\"res_space02\" value=\"바닥\">바닥</input></label>\r\n");
      out.write("							<label for=\"res_space03\" class=\"lbl-checkbox\"> <input type=\"checkbox\" name=\"pRes_space_type\" id=\"res_space03\" value=\"주방\">주방</input></label>\r\n");
      out.write("							<label for=\"res_space04\" class=\"lbl-checkbox\"> <input type=\"checkbox\" name=\"pRes_space_type\" id=\"res_space04\" value=\"욕실\">욕실</input></label>\r\n");
      out.write("							<label for=\"res_space05\" class=\"lbl-checkbox\"> <input type=\"checkbox\" name=\"pRes_space_type\" id=\"res_space05\" value=\"현관\">현관</input></label>\r\n");
      out.write("							<label for=\"res_space06\" class=\"lbl-checkbox\"> <input type=\"checkbox\" name=\"pRes_space_type\" id=\"res_space06\" value=\"발코니/샷시\">발코니/샷시</input></label>\r\n");
      out.write("							<label for=\"res_space07\" class=\"lbl-checkbox\"> <input type=\"checkbox\" name=\"pRes_space_type\" id=\"res_space07\" value=\"조명\">조명</input></label>\r\n");
      out.write("							<label for=\"res_space08\" class=\"lbl-checkbox\"> <input type=\"checkbox\" name=\"pRes_space_type\" id=\"res_space08\" value=\"문\">문</input></label>\r\n");
      out.write("				<!--  			<label for=\"check22\" class=\"lbl-checkbox\"> <input type=\"checkbox\" id=\"check22\">도장</input></label>\r\n");
      out.write("							<label for=\"check23\" class=\"lbl-checkbox\"> <input type=\"checkbox\" id=\"check23\">필름</input></label>\r\n");
      out.write("							<label for=\"check24\" class=\"lbl-checkbox\"> <input type=\"checkbox\" id=\"check24\">목공</input></label>\r\n");
      out.write("							<label for=\"check25\" class=\"lbl-checkbox\"> <input type=\"checkbox\" id=\"check25\">문</input></label>\r\n");
      out.write("							<label for=\"check26\" class=\"lbl-checkbox\"> <input type=\"checkbox\" id=\"check26\">전기</input></label>\r\n");
      out.write("							<label for=\"check27\" class=\"lbl-checkbox\"> <input type=\"checkbox\" id=\"check27\">조명</input></label>\r\n");
      out.write("							<label for=\"check28\" class=\"lbl-checkbox\"> <input type=\"checkbox\" id=\"check28\">가구</input></label>\r\n");
      out.write("							<label for=\"check29\" class=\"lbl-checkbox\"> <input type=\"checkbox\" id=\"check29\">기타</input></label> -->\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("				<!-- 		<h5 class=\"gicho\">기초공사</h5> \r\n");
      out.write("						<div>\r\n");
      out.write("							<label for=\"check30\" class=\"lbl-checkbox\"> <input type=\"checkbox\" id=\"check30\">철거</input></label>\r\n");
      out.write("							<label for=\"check31\" class=\"lbl-checkbox\"> <input type=\"checkbox\" id=\"check31\">설비</input></label>\r\n");
      out.write("							<label for=\"check32\" class=\"lbl-checkbox\"> <input type=\"checkbox\" id=\"check32\">방수</input></label>\r\n");
      out.write("							<label for=\"check33\" class=\"lbl-checkbox\"> <input type=\"checkbox\" id=\"check33\">단열</input></label>\r\n");
      out.write("							<label for=\"check34\" class=\"lbl-checkbox\"> <input type=\"checkbox\" id=\"check34\">확장</input></label>\r\n");
      out.write("						</div> -->\r\n");
      out.write("					</div>\r\n");
      out.write("					<br />\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div>\r\n");
      out.write("					<span><b>상업공간</b></span> <span>▼</span>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=''>\r\n");
      out.write("					<div>\r\n");
      out.write("						<b><span id=\"red\">*</span></b><span> <b>건물 유형(최소 3개 이상)</b></span>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"commercial\" >\r\n");
      out.write("							<label for=\"com_build_all\" class=\"lbl-checkbox\"> <input type=\"checkbox\" name=\"pCom_build_type_all\" id=\"com_build_all\" value=\"\" onclick=\"selectAll3(this)\"></input> 전체</label><br />\r\n");
      out.write("						<div>\r\n");
      out.write("							<label for=\"com_build01\" class=\"lbl-checkbox\"> <input type=\"checkbox\" name=\"pCom_build_type\" id=\"com_build01\" value=\"사무실\">사무실</input></label>\r\n");
      out.write("							<label for=\"com_build02\" class=\"lbl-checkbox\"> <input type=\"checkbox\" name=\"pCom_build_type\" id=\"com_build02\" value=\"상가/매장\">상가/매장</input></label>\r\n");
      out.write("							<label for=\"com_build03\" class=\"lbl-checkbox\"> <input type=\"checkbox\" name=\"pCom_build_type\" id=\"com_build03\" value=\"카페/식당\">카페/식당</input></label>\r\n");
      out.write("							<label for=\"com_build04\" class=\"lbl-checkbox\"> <input type=\"checkbox\" name=\"pCom_build_type\" id=\"com_build04\" value=\"학원/교육\">학원/교육</input></label>\r\n");
      out.write("							<label for=\"com_build05\" class=\"lbl-checkbox\"> <input type=\"checkbox\" name=\"pCom_build_type\" id=\"com_build05\" value=\"숙박/병원\">숙박/병원</input></label>\r\n");
      out.write("							<label for=\"com_build06\" class=\"lbl-checkbox\"> <input type=\"checkbox\" name=\"pCom_build_type\" id=\"com_build06\" value=\"간판\">간판</input></label>\r\n");
      out.write("							<label for=\"com_build07\" class=\"lbl-checkbox\"> <input type=\"checkbox\" name=\"pCom_build_type\" id=\"com_build07\" value=\"기타\">기타</input></label>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<br />\r\n");
      out.write("\r\n");
      out.write("					<div>\r\n");
      out.write("						<b><span id=\"red\">*</span></b><span> <b>가능한 공간</b></span>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"commercial\" >\r\n");
      out.write("						<label for=\"com_space_all\" class=\"lbl-checkbox\"> <input type=\"checkbox\" name=\"pCom_space_type_all\" id=\"com_space_all\" value=\"\" onclick=\"selectAll4(this)\"></input> 전체\r\n");
      out.write("						</label><br />\r\n");
      out.write("						<!--  <h5 class=\"sigong\">시공</h5> -->\r\n");
      out.write("						<div id=\"representative-link\">\r\n");
      out.write("							<label for=\"com_space01\" class=\"lbl-checkbox\"> <input type=\"checkbox\" name=\"pCom_space_type\" id=\"com_space01\" value=\"도배/벽\">도배/벽</input></label>\r\n");
      out.write("							<label for=\"com_space02\" class=\"lbl-checkbox\"> <input type=\"checkbox\" name=\"pCom_space_type\" id=\"com_space02\" value=\"바닥\">바닥</input></label>\r\n");
      out.write("							<label for=\"com_space03\" class=\"lbl-checkbox\"> <input type=\"checkbox\" name=\"pCom_space_type\" id=\"com_space03\" value=\"주방\">주방</input></label>\r\n");
      out.write("							<label for=\"com_space04\" class=\"lbl-checkbox\"> <input type=\"checkbox\" name=\"pCom_space_type\" id=\"com_space04\" value=\"욕실\">욕실</input></label>\r\n");
      out.write("							<label for=\"com_space05\" class=\"lbl-checkbox\"> <input type=\"checkbox\" name=\"pCom_space_type\" id=\"com_space05\" value=\"현관\">현관</input></label>\r\n");
      out.write("							<label for=\"com_space06\" class=\"lbl-checkbox\"> <input type=\"checkbox\" name=\"pCom_space_type\" id=\"com_space06\" value=\"발코니/샷시\">발코니/샷시</input></label>\r\n");
      out.write("							<label for=\"com_space07\" class=\"lbl-checkbox\"> <input type=\"checkbox\" name=\"pCom_space_type\" id=\"com_space07\" value=\"조명\">조명</input></label>\r\n");
      out.write("							<label for=\"com_space08\" class=\"lbl-checkbox\"> <input type=\"checkbox\" name=\"pCom_space_type\" id=\"com_space08\" value=\"문\">문</input></label>\r\n");
      out.write("						</div>\r\n");
      out.write("				<!--  		<h5 class=\"gicho\">기초공사</h5>\r\n");
      out.write("						<div>\r\n");
      out.write("							<label for=\"check68\" class=\"lbl-checkbox\"> <input type=\"checkbox\" id=\"check68\">철거</input></label>\r\n");
      out.write("							<label for=\"check69\" class=\"lbl-checkbox\"> <input type=\"checkbox\" id=\"check69\">설비</input></label>\r\n");
      out.write("							<label for=\"check70\" class=\"lbl-checkbox\"> <input type=\"checkbox\" id=\"check70\">방수</input></label>\r\n");
      out.write("							<label for=\"check71\" class=\"lbl-checkbox\"> <input type=\"checkbox\" id=\"check71\">단열</input></label>\r\n");
      out.write("							<label for=\"check72\" class=\"lbl-checkbox\"> <input type=\"checkbox\" id=\"check72\">확장</input></label>\r\n");
      out.write("							<label for=\"check73\" class=\"lbl-checkbox\"> <input type=\"checkbox\" id=\"check73\">간판</input></label>\r\n");
      out.write("						</div> -->\r\n");
      out.write("					</div>\r\n");
      out.write("					<br />\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div>\r\n");
      out.write("					<label></label>\r\n");
      out.write("				</div>\r\n");
      out.write("			</fieldset>\r\n");
      out.write("\r\n");
      out.write("			<fieldset id=\"representative\">\r\n");
      out.write("		 	  <legend><b>담당자 정보</b></legend>\r\n");
      out.write("				<div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<label><b>주거 담당자</b></label>\r\n");
      out.write("						<div><input type=\"text\" size=\"20\" id=\"pRes_person_name\" name=\"pRes_person_name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ps.pRes_person_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"담당자명\"></div></br>\r\n");
      out.write("						<label><b>담당자 연락처</b></label>\r\n");
      out.write("						<div><input type=\"text\" size=\"20\" id=\"pRes_person_tel\" name=\"pRes_person_tel\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ps.pRes_person_tel}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"담당자 연락처\"></div>\r\n");
      out.write("						<label>\r\n");
      out.write("							<input type=\"checkbox\" aria-hidden=\"false\">\r\n");
      out.write("							<span class=\"\">대표자 정보와 동일 <!----></span>\r\n");
      out.write("						</label>			\r\n");
      out.write("					</div></br>\r\n");
      out.write("					<div>\r\n");
      out.write("						<label><b>상업 담당자</b></label>\r\n");
      out.write("						<div><input type=\"text\" size=\"20\" id=\"pCom_person_name\" name=\"pCom_person_name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ps.pCom_person_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"담당자명\"></div></br>\r\n");
      out.write("						<label id=\"payment-link\"><b>담당자 연락처</b></label>\r\n");
      out.write("						<div><input type=\"text\" size=\"20\" id=\"pCom_person_tel\" name=\"pCom_person_tel\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ps.pCom_person_tel}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"담당자 연락처\"></div>		\r\n");
      out.write("						<label>\r\n");
      out.write("							<input type=\"checkbox\" aria-hidden=\"false\">\r\n");
      out.write("							<span class=\"\">대표자 정보와 동일 <!----></span>\r\n");
      out.write("						</label>								\r\n");
      out.write("					</div>			\r\n");
      out.write("				</div>\r\n");
      out.write("			</fieldset>\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("			<fieldset id=\"payment\">\r\n");
      out.write("		 	  <legend><b>정산 정보</b></legend>\r\n");
      out.write("		 	  \r\n");
      out.write("		 	  <!--  \r\n");
      out.write("				<div>\r\n");
      out.write("					<label><b>세금계산서 이메일</b></label>\r\n");
      out.write("					<div><input type=\"text\" size=\"20\"></div></br>					\r\n");
      out.write("				</div>\r\n");
      out.write("				-->\r\n");
      out.write("				\r\n");
      out.write("				<div>\r\n");
      out.write("					<label><b>입금계좌</b></label>\r\n");
      out.write("					<div><input type=\"text\" size=\"20\" id=\"pAccount_bank\" name=\"pAccount_bank\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ps.pAccount_bank}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"은행명\"></div>\r\n");
      out.write("					<div><input type=\"text\" size=\"20\" id=\"pAccount_name\"name=\"pAccount_name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ps.pAccount_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"예금주\"></div>	\r\n");
      out.write("					<div><input type=\"text\" size=\"20\" id=\"pAccount_num\" name=\"pAccount_num\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ps.pAccount_num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"계좌번호\"></div>						\r\n");
      out.write("				</div></br>\r\n");
      out.write("				<div>\r\n");
      out.write("						<div class=\"representative-01\">\r\n");
      out.write("							<label class=\"upload_image_title\"><b>통장 사본</b></label><br>\r\n");
      out.write("							<div tabindex=\"0\" class=\"upload_image\">\r\n");
      out.write("								<label for=\"pAccount_file\" class=\"upload_lbl\">\r\n");
      out.write("									<img src=\"./images/upload_plus.png\" width=\"40px\" height=\"40px\">\r\n");
      out.write("								</label>\r\n");
      out.write("								<input type=\"file\" id=\"pAccount_file\" name=\"pAccount_file\" accept=\"image/*\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<br>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"representative-02\">\r\n");
      out.write("							<label class=\"upload_image_title\"><b>사업자 등록증 사본</b></label><br>\r\n");
      out.write("							<div tabindex=\"0\" class=\"upload_image\">\r\n");
      out.write("								<label for=\"pBusiness_lic_file\" class=\"upload_lbl\">\r\n");
      out.write("									<img src=\"./images/upload_plus.png\" width=\"40px\" height=\"40px\">\r\n");
      out.write("								</label> \r\n");
      out.write("								<input type=\"file\" id=\"pBusiness_lic_file\" name=\"pBusiness_lic_file\" accept=\"image/*\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<br>\r\n");
      out.write("						</div>\r\n");
      out.write("						<p id=\"red\">* 입금계좌, 통장 사본, 사업자 등록증 사본은 1회만 입력 가능합니다. \r\n");
      out.write("						수정희망 시 집닥담당자 (1600-3069) 에게 문의 해주세요.</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</fieldset>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"data_edit_button_tag\">\r\n");
      out.write("				<input type=\"submit\" id=\"data_edit_bu mtton\" value=\"정보수정\" /> <!-- onclick=\"location.href='date_manage.do'\" -->\r\n");
      out.write("			</div>\r\n");
      out.write("			</form>\r\n");
      out.write("     </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </article>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
