/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-09-28 10:20:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.portfolio;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class p_005fupload_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/header.jsp", out, false);
      out.write("\r\n");
      out.write("<div id=\"introduce_cont\">\r\n");
      out.write("	<h2>시공사례등록</h2>\r\n");
      out.write("	<p>\r\n");
      out.write("		직접 시공한 인테리어의 포트폴리오를 등록할 수 있습니다.<br> 등록된 포트폴리오는 메인홈페이지에서 확인 할 수\r\n");
      out.write("		있습니다.\r\n");
      out.write("	</p>\r\n");
      out.write("	<div>\r\n");
      out.write("		<h4>1. 정보입력 ---> 2. 사진등록 ---> 3. 완료</h4>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div>\r\n");
      out.write("		<span><b>두집</b>에서 계약한 인테리어를 조회하면 쉽게 주요정보를 입력 할 수 있습니다.</span> \r\n");
      out.write("		<input type=\"button\" value=\"불러오기\" onclick=\"loadPortfolioInfo()\">\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("		function loadPortfolioInfo(){\r\n");
      out.write("			$business_num='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${business_num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type:\"post\",\r\n");
      out.write("				url:'loadportfolio_info.do',\r\n");
      out.write("				data:{\r\n");
      out.write("					business_num:$business_num\r\n");
      out.write("				},\r\n");
      out.write("				datatype:\"text\",\r\n");
      out.write("				success: function(result){\r\n");
      out.write("					window.open( \"./portfolio/load_info.jsp\", \"Child\", \"width=800, height=300, top=500, left=500\");\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("</div>\r\n");
      out.write("<form action=\"upload_photo.do\" id=\"portfolio_form\" method=\"post\" onsubmit=\"return portfoilio_check()\">\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("	<fieldset id=\"first_area\">\r\n");
      out.write("		<legend>기본정보</legend>\r\n");
      out.write("		<div>\r\n");
      out.write("			<div id=\"form_sub_title\">\r\n");
      out.write("				<label>제목</label>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"a\">\r\n");
      out.write("				<input type=\"text\" name=\"pf_title\" size=\"30\" id=\"pf_title\"\r\n");
      out.write("					placeholder=\"이보다 더 완벽할 수는 없다\"> <span>0/50</span>\r\n");
      out.write("				<!-- 제목 -->\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"inline_div\">\r\n");
      out.write("			<div id=\"form_sub_title\">\r\n");
      out.write("				<label>공사 유형</label>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- 공사유형 -->\r\n");
      out.write("			<select id=\"sel_type\" name=\"pf_type\" id=\"pf_type\">\r\n");
      out.write("				<option value=\"none\" selected>선택</option>\r\n");
      out.write("				<option value=\"주거공간\">주거공간</option>\r\n");
      out.write("				<option value=\"상업공간\">상업공간</option>\r\n");
      out.write("			</select> <select id=\"sel_house\" name=\"pf_subtype\" id=\"pf_subtype\" disabled>\r\n");
      out.write("				<option value=\"none\" selected>선택</option>\r\n");
      out.write("				<option value=\"아파트\">아파트</option>\r\n");
      out.write("				<option value=\"빌라\">빌라</option>\r\n");
      out.write("				<option value=\"주택\">주택</option>\r\n");
      out.write("				<option value=\"오피스텔\">오피스텔&nbsp;</option>\r\n");
      out.write("			</select> <select id=\"sel_business\" name=\"pf_subtype\" id=\"pf_subtype\" style=\"display: none;\">\r\n");
      out.write("				<option value=\"none\" selected>선택</option>\r\n");
      out.write("				<option value=\"사무실\">사무실</option>\r\n");
      out.write("				<option value=\"상가/매장\">상가/매장</option>\r\n");
      out.write("				<option value=\"카페/식당\">카페/식당</option>\r\n");
      out.write("				<option value=\"학원/교육\">학원/교육</option>\r\n");
      out.write("				<option value=\"숙박/병원\">숙박/병원</option>\r\n");
      out.write("				<option value=\"간판\">간판</option>\r\n");
      out.write("				<option value=\"기타\">기타</option>\r\n");
      out.write("			</select>\r\n");
      out.write("		</div>\r\n");
      out.write("	\r\n");
      out.write("		<div class=\"inline_div\">\r\n");
      out.write("			<div id=\"form_sub_title\">\r\n");
      out.write("				<label>시공 범위</label>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- 시공범위 -->\r\n");
      out.write("			<input type=\"radio\" name=\"pf_range\" value=\"전체 리모델링\">전체 리모델링 <input\r\n");
      out.write("				type=\"radio\" name=\"pf_range\" value=\"부분 리모델링\">부분 리모델링\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"clear\"></div>\r\n");
      out.write("		<div id=\"form_sub_title\">\r\n");
      out.write("			<div id=\"form_sub_title\">\r\n");
      out.write("				<label>주소</label>\r\n");
      out.write("			</div>\r\n");
      out.write("			<input type=\"text\" id=\"sample6_postcode\" readonly placeholder=\"우편번호\"\r\n");
      out.write("				size=\"4\" name=\"pf_zipcode\"> <input type=\"text\" id=\"sample6_address\"  name =\"pf_addr1\" readonly\r\n");
      out.write("				placeholder=\"주소\" size=\"30\"> <input type=\"text\"\r\n");
      out.write("				id=\"sample6_detailAddress\" name =\"pf_addr2\" placeholder=\"상세주소\"> <input\r\n");
      out.write("				type=\"text\" id=\"sample6_extraAddress\" name =\"pf_addr3\" readonly placeholder=\"참고항목\"\r\n");
      out.write("				size=10> <input type=\"button\" value=\"주소검색\"\r\n");
      out.write("				onclick=\"sample6_execDaumPostcode()\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"inline_div\">\r\n");
      out.write("			<div id=\"form_sub_title\">\r\n");
      out.write("				<label>평수</label>\r\n");
      out.write("			</div>\r\n");
      out.write("			<input name=\"pf_area\" id=\"pf_area\" size=\"10\" id=\"parentValue1\"> 평\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"inline_div\">\r\n");
      out.write("			<div id=\"form_sub_title\">\r\n");
      out.write("				<label>공사비용</label>\r\n");
      out.write("			</div>\r\n");
      out.write("			<input type=\"text\" name=\"pf_cost\" id=\"pf_cost\" size=\"10\"> 만원\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"inline_div\">\r\n");
      out.write("			<div id=\"form_sub_title\">\r\n");
      out.write("				<label>공사기간</label>\r\n");
      out.write("			</div>\r\n");
      out.write("			<select name=\"pf_period\" id=\"pf_period\">\r\n");
      out.write("				<option value=\"1\">1</option>\r\n");
      out.write("				<option value=\"2\">2</option>\r\n");
      out.write("				<option value=\"3\">3</option>\r\n");
      out.write("				<option value=\"4\">4</option>\r\n");
      out.write("				<option value=\"5\">5</option>\r\n");
      out.write("				<option value=\"6\">6</option>\r\n");
      out.write("				<option value=\"7\">7</option>\r\n");
      out.write("				<option value=\"8\">8</option>\r\n");
      out.write("				<option value=\"9\">9</option>\r\n");
      out.write("			</select>주\r\n");
      out.write("		</div>\r\n");
      out.write("	</fieldset>\r\n");
      out.write("	<!-- 여기까지 첫번째 입력 영역-->\r\n");
      out.write("	<fieldset>\r\n");
      out.write("		<legend>디자인(시공컨셉)</legend>\r\n");
      out.write("		<div id=\"form_sub_title\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<input type=\"radio\" value=\"모던\" name=\"pf_concept\">모던 <input type=\"radio\"\r\n");
      out.write("			value=\"미니멀\" name=\"pf_concept\">미니멀 <input type=\"radio\" value=\"내추럴\" name=\"pf_concept\">내추럴\r\n");
      out.write("		<input type=\"radio\" value=\"빈티지\" name=\"pf_concept\">빈티지 <input type=\"radio\"\r\n");
      out.write("			value=\"심플\" name=\"pf_concept\">심플 <input type=\"radio\" value=\"럭셔리\" name=\"pf_concept\">럭셔리\r\n");
      out.write("	</fieldset>\r\n");
      out.write("	<fieldset>\r\n");
      out.write("		<legend>소개글</legend>\r\n");
      out.write("		<textarea rows=10% cols=100% name=\"pf_introduction\" id=\"pf_introduction\" style=\"width: 100%; resize: none;\">(EX. 따듯함이 느껴지는 원목과 화이트 컬러의 내추럴 스타일, 33평 아파트 인테리어 입니다.)</textarea>\r\n");
      out.write("	</fieldset>\r\n");
      out.write("	<fieldset>\r\n");
      out.write("		<legend>맺음말</legend>\r\n");
      out.write("		<textarea rows=\"7\" cols=100% name=\"pf_closing\" id=\"pf_closing\" style=\"width: 100%; resize: none;\">(EX. 지금까지 서울 강남구 논현동 33평 아파트 인테리어 였습니다.)</textarea>\r\n");
      out.write("	</fieldset>\r\n");
      out.write("	<fieldset id=\"f_button\">\r\n");
      out.write("		<input type=\"submit\" value=\"사진등록\"> <input type=\"reset\"\r\n");
      out.write("			value=\"초기화\">\r\n");
      out.write("	</fieldset>\r\n");
      out.write("</form>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
